### ISSUE TITLE
Erro numero 5383e6a601fa9231511b341997c11bcd1a64586a v2.7.5

### ISSUE THREAD

**Issue by dzinxd** [UNIVALI-LITE/Portugol-Studio#1007]
> Esta issue foi gerada automaticamente

[pressione o botao "copiar erro" no Portugol Studio e cole o erro aqui antes de enviar]

br.univali.ps.nucleo.ExcecaoAplicacao: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at br.univali.ps.nucleo.TratadorExcecoes.transformarExcecao(TratadorExcecoes.java:278)
	at br.univali.ps.nucleo.TratadorExcecoes.exibirExcecao(TratadorExcecoes.java:43)
	at br.univali.ps.ui.abas.AbaCodigoFonte$AcaoExecucao.actionPerformed(AbaCodigoFonte.java:1099)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at br.univali.ps.ui.abas.AbaCodigoFonte$AcaoExecucao.actionPerformed(AbaCodigoFonte.java:1090)
	... 40 more
Caused by: java.lang.NullPointerException
	at br.univali.portugol.nucleo.execucao.gerador.helpers.Utils.getNomeTipoJava(Utils.java:282)
	at br.univali.portugol.nucleo.execucao.gerador.helpers.GeradorDeclaracaoVariavel.gera(GeradorDeclaracaoVariavel.java:107)
	at br.univali.portugol.nucleo.execucao.gerador.GeradorCodigoJava$VisitorGeracaoCodigo.visitar(GeradorCodigoJava.java:527)
	at br.univali.portugol.nucleo.execucao.gerador.GeradorCodigoJava$VisitorGeracaoCodigo.visitar(GeradorCodigoJava.java:108)
	at br.univali.portugol.nucleo.asa.NoVetor.aceitar(NoVetor.java:54)
	at br.univali.portugol.nucleo.execucao.gerador.helpers.GeradorDeclaracaoVariavel.gera(GeradorDeclaracaoVariavel.java:147)
	at br.univali.portugol.nucleo.execucao.gerador.GeradorCodigoJava$VisitorGeracaoCodigo.visitar(GeradorCodigoJava.java:520)
	at br.univali.portugol.nucleo.execucao.gerador.GeradorCodigoJava$VisitorGeracaoCodigo.visitar(GeradorCodigoJava.java:108)
	at br.univali.portugol.nucleo.asa.NoDeclaracaoVetor.aceitar(NoDeclaracaoVetor.java:84)
	at br.univali.portugol.nucleo.execucao.gerador.helpers.Utils.visitarBlocos(Utils.java:264)
	at br.univali.portugol.nucleo.execucao.gerador.helpers.GeradorDeclaracaoMetodo.gera(GeradorDeclaracaoMetodo.java:67)
	at br.univali.portugol.nucleo.execucao.gerador.GeradorCodigoJava$VisitorGeracaoCodigo.geraMetodos(GeradorCodigoJava.java:335)
	at br.univali.portugol.nucleo.execucao.gerador.GeradorCodigoJava.gera(GeradorCodigoJava.java:104)
	at br.univali.portugol.nucleo.compilador.Compilador.geraPrograma(Compilador.java:163)
	at br.univali.portugol.nucleo.compilador.Compilador.compilar(Compilador.java:104)
	at br.univali.portugol.nucleo.Portugol.compilar(Portugol.java:29)
	at br.univali.portugol.nucleo.Portugol.compilarParaExecucao(Portugol.java:48)
	at br.univali.ps.ui.abas.AbaCodigoFonte.lambda$compilaProgramaParaExecucao$4(AbaCodigoFonte.java:1906)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Código do Erro:
programa
{
	inclua biblioteca Util
	funcao inteiro numero(inteiro n[]){
		inteiro maior_valor = 0
		para(inteiro contador = 0; contador < Util.numero_elementos(n); contador++){
			se(n[contador] > maior_valor){
				maior_valor = n[contador]
			}
		}
		retorne maior_valor
	}
	funcao inicio()
	{
		inteiro num[] = {sorteia(1, 10)}
		escreva("O maior valor que eu encontrei foi ", numero(num))
	}
}

**Comment by AdsonEsteves** [comment]
@dzinxd 
Obrigado pelo reporte.
Coloque a chamada de funcao do sorteia em uma variavel separada, que acredito que vá dar o efeito que deseja

``
inteiro a = sorteia(1, 10)
     
          inteiro num[] = {a}
          escreva("O maior valor que eu encontrei foi ", numero(num))

``

Vamos registrar a issue, pois não deveria gerar erro.
