### ISSUE TITLE
Exceção disparada ao abrir o programa.

### ISSUE THREAD

**Issue by rytix** [UNIVALI-LITE/Portugol-Studio#103]
A seguinte exceção é disparada aleatoriamente ao abrir o programa:
![image](https://cloud.githubusercontent.com/assets/7809511/13474391/99389cbe-e09c-11e5-8c30-dca4e49c230a.png)

Pelo seu comportamento aleatório parece que é algum bug envolvendo threads.

**Comment by AdsonEsteves** [comment]
Aconteceu também quando foi baixado a atualização de teste

```JAVA
GRAVE: Exce??o capturada [br.univali.ps.nucleo.TratadorExcecoes exibirExcecao] 
br.univali.ps.nucleo.ExcecaoAplicacao: java.lang.RuntimeException: JRootPane for PopupLayer cannot be found
	at br.univali.ps.nucleo.TratadorExcecoes.uncaughtException(TratadorExcecoes.java:199)
	at java.lang.ThreadGroup.uncaughtException(Unknown Source)
	at java.lang.ThreadGroup.uncaughtException(Unknown Source)
	at java.awt.EventDispatchThread.processException(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.RuntimeException: JRootPane for PopupLayer cannot be found
	at com.alee.managers.popup.PopupManager.getPopupLayer(PopupManager.java:222)
	at com.alee.managers.popup.PopupManager.getPopupLayer(PopupManager.java:209)
	at com.alee.managers.notification.NotificationManager.showNotification(NotificationManager.java:495)
	at com.alee.managers.notification.NotificationManager.showNotification(NotificationManager.java:483)
	at br.univali.ps.ui.FabricaDicasInterface.lambda$mostrarNotificacao$6(FabricaDicasInterface.java:93)
	at br.univali.ps.ui.FabricaDicasInterface$$Lambda$16/20021567.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$400(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	... 6 more

```

**Comment by AlissonSteffens** [comment]
Baphomet age novamente...

**Comment by noschang** [comment]
Vejam a seguinte linha do stack de exceções:

at com.alee.managers.popup.PopupManager.getPopupLayer(PopupManager.java:222)

Esta linha indica que o método getPopupLayer da classe PopupManager quem jogou a exceção.
Ao que tudo indica esta classe é do WebLaf, pois está no pacote "com.alee". 

E ao olhar a descrição do erro, ela fala sobre o "JRootPane" não ter sido encontrado.

A partir disso, dá pra inferir algumas coisas:

1. A classe que está gerando o erro é a classe que cria as notificações popup do WebLaf

2. O JRootPane é o painel raíz de todo JFrame. Se ele não está sendo encontrado pelo WebLaf, é porque ele ainda não foi criado no momento que o popup é exibido

3. Se o JRootPane não foi criado, é bem provável que o próprio JFrame não existe ou não esteja visível no momento que o popup tenta exibir

4. Se o erro ocorre às vezes sim, às vezes não. É bem provável que o popup esteja sendo exibido a partir de uma nova Thread, que às vezes é disparada após a criação do JFrame, e às vezes é disparada antes

Com isso em mente, o próximo passo é descobrir todos os locais do código onde os popups são disparados e tentar identificar se em algum momento nós mandamos exibir algum popup antes da criação do JFrame e dos componentes

**Comment by AlissonSteffens** [comment]
A única notificação que pode ser enviada a qualquer momento do programa é a de resolução... Mas ela só aparece caso a tela fique menor ou igual a 800x600

**Comment by noschang** [comment]
No meu Linux, ela aperece quando a tela está abrindo. Pois no Linux, tem aquela viadagem da janela começar pequena e ir abrindo com efeito de zoom.

É o mesmo problema que acontece quando tu vai rodar os exempos dos jogos e aí a tela acaba ficando cortada.

Em teoria, enquanto o efeito de zoom está sendo aplicado pelo sistema operacional, são disparados vários eventos de "Resize", cada um deles disparando uma nova notificação.

Talvez o mesmo ocorra em algumas versões do Windows que tenham algum tipo de efeito parecido habilitado. Isto pode explicar porque o erro ocorre pro @rytix mas no seu computador não.

Uma coisa que acontece é que em teoria, durante este efeito de zoom, o JFrame e todo seu conteúdo estão em um estado inválido, fazendo com que o Popup não encontre o JRootPane para ser "docado". 

Dêem uma lida aqui: 
https://docs.oracle.com/javase/7/docs/api/java/awt/Component.html#isValid%28%29

Talvez precisemos fazer uma verificação de "isValid()" antes de exibir o popup.
Acredito que se resolvermos o problemo aqui, também conseguimos resolver o bug na biblioteca gráficos permitindo que o método "renderizar()" só seja executado quando o método "isValid()" do JFrame retornar true.

**Comment by elieserdejesus** [comment]
Verifiquem também se todas as exibições da popup realmente estão sendo executadas na **thread do swing**, porque se não for o caso coisas estranhas e imprevisíveis podem acontecer :)

**Comment by AlissonSteffens** [comment]
Estão sim
![image](https://cloud.githubusercontent.com/assets/6234230/13504259/87c71c9c-e152-11e5-839c-56bd2b20099f.png)

**Comment by AdsonEsteves** [comment]
Não só no momento que se abre, mas no meu computador, após a uns 3 minutos o mesmo erro apareceu

**Comment by rytix** [comment]
uns 20s aqui até aparecer o erro novamente.
![image](https://cloud.githubusercontent.com/assets/7809511/13509033/4f949014-e168-11e5-969c-53f09c7d7ddf.png)

**Comment by AdsonEsteves** [comment]
O bug está na notificação de atualização. Precisamente se a tela atual selecionada não for o Portugol(exemplo estiver no NetBeans), e o tempo da notificação aparecer chega, acontece o erro. A notificação vai tentar aparecer na janela que estiver selecionada no momento(bug já relatado anteriormente) e se essa tela for de outro programa, que não o portugol, o erro acontece.

**Comment by noschang** [comment]
Parabéns @AdsonEsteves. Isto é uma grande pista! Agora já temos idéia de como podemos resolver!

**Comment by AlissonSteffens** [comment]
Resolvido, ver PullRequest #105
