### ISSUE TITLE
Erro numero d5167a959a1825b3da092f997ff3326921ff3a75 v2.7.5

### ISSUE THREAD

**Issue by Myloveken** [UNIVALI-LITE/Portugol-Studio#1039]
> Esta issue foi gerada automaticamente

[pressione o botao "copiar erro" no Portugol Studio e cole o erro aqui antes de enviar]

**Comment by Myloveken** [comment]
br.univali.ps.nucleo.ExcecaoAplicacao: br.univali.ps.plugins.base.ErroInstalacaoPlugin: Erro ao instalar o plugin 'Nova Pasta'
	at br.univali.ps.nucleo.TratadorExcecoes.transformarExcecao(TratadorExcecoes.java:278)
	at br.univali.ps.nucleo.TratadorExcecoes.exibirExcecao(TratadorExcecoes.java:43)
	at br.univali.ps.plugins.base.GerenciadorPlugins$1.run(GerenciadorPlugins.java:118)
	at java.lang.Thread.run(Thread.java:748)
Caused by: br.univali.ps.plugins.base.ErroInstalacaoPlugin: Erro ao instalar o plugin 'Nova Pasta'
	... 2 more
Caused by: java.io.FileNotFoundException: C:\Users\Dell\AppData\Roaming\Microsoft\Windows\Recent\Nova Pasta\Nova Pasta (O sistema n￣o pode encontrar o arquivo especificado)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at br.univali.ps.ui.utils.UnzipUtility.unzip(UnzipUtility.java:35)
	at br.univali.ps.plugins.base.GerenciadorPlugins$1.run(GerenciadorPlugins.java:116)
	... 1 more

**Comment by Myloveken** [comment]
Ok
