### ISSUE TITLE
Erro numero f687ab677275580babb48d56a16ddedd485273ca v2.7.5

### ISSUE THREAD

**Issue by gsr2005g** [UNIVALI-LITE/Portugol-Studio#1043]
> Esta issue foi gerada automaticamente

br.univali.ps.nucleo.ExcecaoAplicacao: java.lang.ArrayIndexOutOfBoundsException
	at br.univali.ps.nucleo.TratadorExcecoes.uncaughtException(TratadorExcecoes.java:145)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.awt.EventDispatchThread.processException(EventDispatchThread.java:227)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:219)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ArrayIndexOutOfBoundsException

Código do Erro:
programa{

  /*  Aula 101: Faça o jogo da velha em Portugol.
   * 
   * Escrito por Wagner Gaspar
   * Março de 2021
   *   
   *     |  |
   *   --------
   *     |  |
   *   --------
   *     |  |
  */
     //variavel global
      caracter jogo[3][3], O, X
       inteiro i, j, linha, coluna, jogador=1, ganhou=0, jogadas=0, opcao

       
      funcao inicializarjogo(){
       
        para(i = 0; i < 3; i++){
           para(j = 0; j < 3; j++){
             jogo[i][j] = ' '
           }
         } 
      }
      funcao sms(){
         // impressão do tabuleiro
	        escreva("\n\n 0   1    2\n\n")
	     
	        para(i = 0; i < 3; i++){
	           para(j = 0; j < 3; j++){
	            escreva(" ", jogo[i][j])
	            se(j < 2)
	              escreva(" | ")
	            se(j == 2)
	              escreva("  ", i)
	          }
	          se(i < 2)
	            escreva("\n------------")
	          escreva("\n")
	        }
	      	
	      }

	 funcao cordenadas(inteiro jogador){
		
		 faca{
		     faca{
		       escreva("\nJogador ",jogador, " digite linha e coluna da posição desejada: ")
		       leia(linha, coluna)
		     }enquanto(linha < 0 ou linha > 2 ou coluna < 0 ou coluna > 2)
		}enquanto(jogo[linha][coluna] != ' ') 	
	 }

      funcao inteiro salvarjogadas (inteiro jogador){

          se(jogador == 1){
          jogo[linha][coluna] = 'O'
          jogador++
        }
        senao{
          jogo[linha][coluna] = 'X'
         // jogador = 1
          retorne 1
        }	
      }
      funcao inteiro ganhouporlinha(caracter i){
        para(i = 0; i < 3; i++){
          se(jogo[i][0] == 'O' e jogo[i][1] == 'O' e jogo[i][2] == 'O')
            ganhou = 1
        }
      	RETORNO
      }
      
      
      funcao inicio(){

    faca{
     inicializarjogo()
  
      faca{
       sms()
       cordenadas(jogador)
        jogadas += salvarjogadas(jogador)

      
        
        // verificar ganhador por linhas
        ganhouporlinha('O')
         ganhouporlinha('X')
       para(i = 0; i < 3; i++){
          se(jogo[l][0] == 'X' e jogo[l][1] == 'X' e jogo[l][2] == 'X')
            ganhou = 2
        }
        
        // verificar ganhador por colunas
        para(c = 0; c < 3; c++){
          se(jogo[0][c] == '0' e jogo[1][c] == '0' e jogo[2][c] == '0')
            ganhou = 1
        }
    
        para(c = 0; c < 3; c++){
          se(jogo[0][c] == 'X' e jogo[1][c] == 'X' e jogo[2][c] == 'X')
            ganhou = 2
        }
        // verificar ganhador na diagonal principal
        se(jogo[0][0] == '0' e jogo[1][1] == '0' e jogo[2][2] == '0')
          ganhou = 1
    
        se(jogo[0][0] == 'X' e jogo[1][1] == 'X' e jogo[2][2] == 'X')
          ganhou = 2
        
        // verificar ganhador na diagonal secundária
        se(jogo[0][2] == '0' e jogo[1][1] == '0' e jogo[2][0] == '0')
          ganhou = 1  
    
        se(jogo[0][2] == 'X' e jogo[1][1] == 'X' e jogo[2][0] == 'X')
          ganhou = 2
      }enquanto(ganhou == 0 e jogadas < 9)
  
      // impressão do tabuleiro
      sms()
  
      se(ganhou == 1)
        escreva("\n\tParabéns Jogador 1. Você ganhou!\n\n")

      se(ganhou == 2)
        escreva("\n\tParabéns Jogador 2. Você ganhou!\n\n")
  
      escreva("Digite 1 para jogar novamente: ")
      leia(opcao)
    }enquanto(opcao == 1)
  }
}

**Comment by AdsonEsteves** [comment]
@gsr2005g 
Isso acontece sempre?
