### ISSUE TITLE
Corrigir builds e gerar instaladores nas 3 plataformas (Windows, Linux e Mac)

### ISSUE THREAD

**Issue by elieserdejesus** [UNIVALI-LITE/Portugol-Studio#202]
- [x] verificar build no Windows
- [x] verificar build no Mac
- [x] verificar build no Linux

- [x] Corrigir nome do programa (Lancador) no Mac
- [x] Corrigir ícone do Docker no Mac
- [x] Corrigir opções do botão direito do mouse no windows (Abrir, executar no console, executar no modo gráfico)
- [x] Corrigir ícone do Linux no Launcher
- [x] Corrigir nome da aplicação no Launcher do Linux
- [x] Corrigir mensagem de erro que aparece no final da instalação no linux
- [x] Corrigir retangulo estranho que aparece no linux durante a execução passo a passo
- [x] Corrigir execução via linha de comando no linux
- [x] Arquivos .por não estão sendo associados com o PS no Linux 64 bits (está funcionando em 32 bits)

**Comment by elieserdejesus** [comment]
Instalador funcionando corretamente no Windows.

O instalador do Mac foi gerador corretamente mas depois de instalado o PS não inicia.

**Comment by noschang** [comment]
@elieserdejesus, verifique na classe "Caminhos" e na classe "Configuracoes", se existe um método para resolver o caminho do Javac quando está no Mac. É bem provável que ele não esteja encontrando o Javac nesta plataforma, da mesma maneira que não estava encontrando no Linux.

**Comment by elieserdejesus** [comment]
Reporting: gerei o instalador do Mac novamente usando as correções que foram feitas anteriormente e o executável não abre. O script executável do .app está com o problema de quebra de linha que já tínhamos resolvido em https://github.com/UNIVALI-LITE/Portugol-Instalador/commit/be23ff82f45e6c73b5f890faf55603b2a4875ee2. 

Talvez o instalador esteja gerando o script com as quebras de linhas no padrão windows (estou gerando os instaladores no Windows). Teríamos que tentar gerar o instalador em outra máquina para ver se é isso mesmo. Podes tentar isso @noschang ?

**Comment by elieserdejesus** [comment]
@noschang , @AlissonSteffens , @AdsonEsteves , boas notícias!

Configurei o meu git para não modificar a quebra de linha dos arquivos 
```
git config --global core.autocrlf false
```

deletei o meu repositório Portugol-Instalador e clonei esse repositório novamente (agora mantendo a quebra de linha correta no script que estava dando erro).

Gerei o instalador do mac e agora o app está executando. A quebra de linha do script do Mac está sendo mantida pelo BitRock. Então uma solução seria todos usarem a mesma configuração de quebra de linha no git. Acho (alguém se habilita para pesquisar isso?) que é possível deixar um arquivo **.gitattributes** no repositório especificando essa configuração para o projeto, e essa configuração sobrescreve a configuração global do git. 

Entretanto agora tive um problema de permissão de aquivo quando o PS tenta criar o mutex. Alguma luz @noschang ?

````
Can't load log handler "java.util.logging.FileHandler"
java.nio.file.AccessDeniedException: log.txt.lck
java.nio.file.AccessDeniedException: log.txt.lck
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:177)
	at java.nio.channels.FileChannel.open(FileChannel.java:287)
	at java.nio.channels.FileChannel.open(FileChannel.java:335)
	at java.util.logging.FileHandler.openFiles(FileHandler.java:459)
	at java.util.logging.FileHandler.<init>(FileHandler.java:263)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.logging.LogManager$5.run(LogManager.java:966)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.logging.LogManager.loadLoggerHandlers(LogManager.java:958)
	at java.util.logging.LogManager.initializeGlobalHandlers(LogManager.java:1578)
	at java.util.logging.LogManager.access$1500(LogManager.java:145)
	at java.util.logging.LogManager$RootLogger.accessCheckedHandlers(LogManager.java:1667)
	at java.util.logging.Logger.getHandlers(Logger.java:1777)
	at java.util.logging.Logger.log(Logger.java:735)
	at java.util.logging.Logger.doLog(Logger.java:765)
	at java.util.logging.Logger.log(Logger.java:788)
	at br.univali.ps.ui.Lancador.start(Lancador.java:111)
	at br.univali.ps.ui.Lancador.main(Lancador.java:39)
SEVERE [09:47:13:952]: Exceção capturada [br.univali.ps.nucleo.TratadorExcecoes exibirExcecao] 
br.univali.ps.nucleo.Mutex$ErroCriacaoMutex: Erro ao criar o Mutex do Portugol Studio
	at br.univali.ps.nucleo.MutexImpl.inicializar(MutexImpl.java:66)
	at br.univali.ps.nucleo.PortugolStudio.iniciarNovaInstancia(PortugolStudio.java:193)
	at br.univali.ps.nucleo.PortugolStudio.iniciar(PortugolStudio.java:178)
	at br.univali.ps.ui.Lancador.start(Lancador.java:130)
	at br.univali.ps.ui.Lancador.main(Lancador.java:39)
Caused by: java.io.FileNotFoundException: /Applications/UNIVALI/Portugol Studio.app/Contents/Resources/IDE/mutex (Permission denied)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at br.univali.ps.nucleo.MutexImpl.inicializar(MutexImpl.java:57)
	... 4 more
````

**Comment by elieserdejesus** [comment]
@noschang , dei permissão de escrita na pasta **IDE** criada pelo instalador e funcionou. Acho que o installer não está setando as permissões das pastas que estão dentro de *MacOs/Contents*. 

Por outro lado, não é estranho que o PS esteja criando o mutex dentro de **/Applications/UNIVALI/Portugol Studio.app/Contents/Resources/IDE/mutex**?  

Acho que o padrão no Mac é usar **Contents** apenas para leitura e usar **~/Library/Application Support/** para escrita. Acho que usando **Application Support** não seria necessário mexer em privilégio nenhum nas pastas criadas pelo instalador. O que achas?

**Comment by noschang** [comment]
Por mim tudo bem. É que o padrão é ele criar o Mutex dentro da pasta de instalação, mas é fácil mudar pra ele criar em outro diretório (como o temp, por exemplo).

Se quiser mudar isso não me oponho, só deves garantir que a criação e exclusão do mutex seja feita corretamente nas 3 plataformas.

**Comment by elieserdejesus** [comment]
@noschang , @AdsonEsteves  e @AlissonSteffens , não é necessário mexer nas configurações globais do git para resolver o problema das quebras de linha. É possível definir quebras de linha específicas para cada arquivo no arquivo *.gitattributes*. Fix isso nos scripts do Mac https://github.com/UNIVALI-LITE/Portugol-Instalador/commit/0022b4ed0ead0e1406e549efece6cc3cb764b51e

**Comment by elieserdejesus** [comment]
Mutex sendo criado no diretório temporário https://github.com/UNIVALI-LITE/Portugol-Studio/commit/002cfa3062a76430b77bbdb6d5999cbd2ecca8be

**Comment by elieserdejesus** [comment]
Build do mac funcionando!

**Comment by elieserdejesus** [comment]
@noschang , na versão anterior o Inicializador invocava o .jar do PS e passada os parâmetros da JVM para setar o uso de memória, ícone (no Docker), nome da aplicação no Mac, etc.

Na versão atual esses parâmetros que eram passados pelo inicializador serão passados diretamente, certo?

Eu vi que o **script executável** do Mac aceita parâmetrose e depois invoca o .jar do PS com os parâmetros que foram recebidos. Se entendi o esquema corretamente o que precisamos fazer agora é alterar o **script executável** para passar os parâmetros diretamente na invocação do .jar, certo?  O scripr do Mac, por exemplo, ainda vai precisar receber parâmetros ou bastaria invocar o jar diretamente com os parâmetros *fixos*, hardcoded no próprio script?

**Comment by noschang** [comment]
@elieserdejesus. É isso mesmo, estes parâmetros passam a ser hard coded nos scripts, tanto do MAC quanto do Linux.

A única exceção eu acredito que seja no caso do Windows, porque além de setar estes parâmetros nos arquivos BAT, também é necessário ajustar estes parâmetros nos atalhos da área de trabalho gerados pelo instalador (se não estou equivocado).

**Comment by elieserdejesus** [comment]
Funcionou @noschang !

Outra coisa: existem dois arquivos scripts **executar-console-mac.command** e **executar_studio-mac.command**. Eles ainda serão usados na versão nova?

**Comment by noschang** [comment]
Sim

**Comment by elieserdejesus** [comment]
@noschang , good news! Aquelas alterações que foram feitas no instalador resolveram a mensagem de erro na instalação **do Linux** e também resolveram o problema do ícone e do nome da aplicação no Launcher.  

**Os instaladores das 3 plataformas estão funcionando**, só falta corrigir a execução via linha de comando no Linux. Aquele auto completar para o comando **portugol-studio** não está funcionando no momento (Testado no Ubuntu).

**Comment by elieserdejesus** [comment]
A execução  via linha de comando no Linux está funcionando!

**Comment by elieserdejesus** [comment]
fechando a issue, todos os instaladores funcionando corretamente!
