### ISSUE TITLE
Escolha caso gera erro com constantes e caso contrario.

### ISSUE THREAD

**Issue by Rafaelfcosta** [UNIVALI-LITE/Portugol-Studio#309]
_From @rytix on June 8, 2017 19:46_

Funciona:
![image](https://user-images.githubusercontent.com/7809511/26947643-d2d8f114-4c69-11e7-89a6-3c2fdfc03bd8.png)

Não Funciona:
![image](https://user-images.githubusercontent.com/7809511/26947452-2040f038-4c69-11e7-8213-d1c2604a911b.png)

Código:

```
programa
{
	const inteiro MUITO_FACIL = 0
	
	funcao inicio()
	{
		teste()
	}
	funcao teste()
	{
		escolha (1)
		{
			caso MUITO_FACIL	:
			caso contrario		:
		}
	}
}

```
Stack Trace:
```
GRAVE [16:45:39:339]: null [br.univali.ps.ui.abas.AbaCodigoFonte$AcaoExecucao$1 run] 
java.lang.NullPointerException
	at br.univali.portugol.nucleo.asa.NoReferenciaVariavel.montarTrechoCodigoFonte(NoReferenciaVariavel.java:53)
	at br.univali.portugol.nucleo.asa.NoExpressao.getTrechoCodigoFonte(NoExpressao.java:70)
	at br.univali.portugol.nucleo.asa.NoNao.montarTrechoCodigoFonte(NoNao.java:61)
	at br.univali.portugol.nucleo.asa.NoExpressao.getTrechoCodigoFonte(NoExpressao.java:70)
	at br.univali.portugol.nucleo.asa.NoOperacao.montarTrechoCodigoFonte(NoOperacao.java:98)
	at br.univali.portugol.nucleo.asa.NoExpressao.getTrechoCodigoFonte(NoExpressao.java:70)
	at br.univali.portugol.nucleo.execucao.gerador.helpers.Utils.getTrechoCodigoFonte(Utils.java:342)
	at br.univali.portugol.nucleo.execucao.gerador.helpers.Utils.geraParadaPassoAPasso(Utils.java:370)
	at br.univali.portugol.nucleo.execucao.gerador.helpers.GeradorSwitchCase.geraSeSenao(GeradorSwitchCase.java:105)
	at br.univali.portugol.nucleo.execucao.gerador.GeradorCodigoJava$VisitorGeracaoCodigo.visitar(GeradorCodigoJava.java:749)
	at br.univali.portugol.nucleo.execucao.gerador.GeradorCodigoJava$VisitorGeracaoCodigo.visitar(GeradorCodigoJava.java:94)
	at br.univali.portugol.nucleo.asa.NoEscolha.aceitar(NoEscolha.java:107)
	at br.univali.portugol.nucleo.execucao.gerador.helpers.Utils.visitarBlocos(Utils.java:286)
	at br.univali.portugol.nucleo.execucao.gerador.helpers.GeradorDeclaracaoMetodo.gera(GeradorDeclaracaoMetodo.java:65)
	at br.univali.portugol.nucleo.execucao.gerador.GeradorCodigoJava$VisitorGeracaoCodigo.geraMetodos(GeradorCodigoJava.java:309)
	at br.univali.portugol.nucleo.execucao.gerador.GeradorCodigoJava.gera(GeradorCodigoJava.java:90)
	at br.univali.portugol.nucleo.Compilador.geraPrograma(Compilador.java:141)
	at br.univali.portugol.nucleo.Compilador.compilar(Compilador.java:92)
	at br.univali.portugol.nucleo.Portugol.compilar(Portugol.java:30)
	at br.univali.portugol.nucleo.Portugol.compilarParaExecucao(Portugol.java:49)
	at br.univali.ps.ui.abas.AbaCodigoFonte.compilaProgramaParaExecucao(AbaCodigoFonte.java:1723)
	at br.univali.ps.ui.abas.AbaCodigoFonte.access$1600(AbaCodigoFonte.java:88)
	at br.univali.ps.ui.abas.AbaCodigoFonte$AcaoExecucao$1.run(AbaCodigoFonte.java:981)
 

```

_Copied from original issue: UNIVALI-LITE/Portugol-Nucleo#111_

**Comment by noschang** [comment]
Duplicata da issue #294
