### ISSUE TITLE
Erro não identificado - inspetor de variáveis

### ISSUE THREAD

**Issue by andrelms** [UNIVALI-LITE/Portugol-Studio#336]
Quando um estudante não inicializa uma variável apresenta duas mensagens de erro: Erro de compilação e em sequência erro de inicialização de variável. 

No entanto, se ele arrasta uma variável para o inspetor ele cospe um null pointer quando ele tenta compilar o código

**Exception: **

br.univali.ps.nucleo.ExcecaoAplicacao: java.lang.NullPointerException
	at br.univali.ps.nucleo.TratadorExcecoes.uncaughtException(TratadorExcecoes.java:167)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.awt.EventDispatchThread.processException(EventDispatchThread.java:223)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:215)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NullPointerException
	at br.univali.portugol.nucleo.asa.VisitanteNulo.visitar(VisitanteNulo.java:14)
	at br.univali.portugol.nucleo.asa.ASAPrograma.aceitar(ASAPrograma.java:71)
	at br.univali.ps.ui.inspetor.InspetorDeSimbolos$TarefaReconstrucaoNosInspecionados.run(InspetorDeSimbolos.java:699)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	... 5 more
<img width="1279" alt="captura de tela 2017-09-10 as 18 43 44" src="https://user-images.githubusercontent.com/3330769/30253273-44b03aee-9658-11e7-9606-37fdd92ff724.png">

**Comment by elieserdejesus** [comment]
Posso resolver essa.

**Comment by elieserdejesus** [comment]
@andrelms , não consegui reproduzir o erro. Podes postar esse código?

**Comment by andrelms** [comment]
programa
{	
	inclua biblioteca Matematica --> mat
	funcao inicio()
	{
		real pre, reservada
		cadeia prod
		inteiro vl
		caracter op

		faca
		{
			escreva("Digite o produto: ")
			leia(prod)
			faca
			{
				escreva("\nDigite o preço do produto: ")
				leia(pre)
			}enquanto( pre == 0)

			escreva("[0] - A vista '10 % de desconto' ")
			escreva("\n")
			escreva("[1] - 1x 'sem desconto' ")
			escreva("\n")
			escreva("[2] - 2x '5% de acrecimo' ")
			escreva("\n")
			escreva("[3] - 3x '10% de acrecimo' ")
			escreva("\n")
			escreva("[4] - 4x '10% de acrecimo' ")
			escreva("\n")
			escreva("[5] - 5x '10% de acrecimo' ")

			escreva("\n Escolha uma opção: ")
			leia(vl)

			escolha (vl)
			{
				caso 0 : 
				reservada = pre - pre * 0.1
				escreva(prod, " A vista 10% de Ddesconto", mat.arredondar(reservada, 2))
				pare 

				caso 1 :
				escreva(prod, "Em 1x sem desconto", mat.arredondar(reservada,2))
				pare

				caso 2 :
				reservada = pre + pre * 0.05 / 2
				escreva(prod, "Em 2x com 5% de acrecimo", mat.arredondar(reservada,2))
				pare

				caso 3 :
				reservada = pre + pre * 0.10 / 3
				escreva(prod, "Em 3x com 10% de acrecimo", mat.arredondar(reservada,2))
				pare

				caso 4 :
				reservada = pre + pre * 0.10 / 4
				escreva(prod, "Em 4x com 10% de acrecimo", mat.arredondar(reservada,2))
				pare

				caso 5 :
				reservada = pre + pre *  0.10 / 5
				escreva(prod, "Em 5x com 10% de acrecimo", mat.arredondar(reservada,2))
				pare

			
			}

			escreva("\nDigite s para novo calculo")
			leia(op)	
			
			
		}enquanto (op =='s' ou op =='S')
		
		
	}
}

**Comment by AlissonSteffens** [comment]
@elieserdejesus atualizei tua mensagem ✌️

**Comment by noschang** [comment]
@elieserdejesus, quando você for resolver uma issue, siga o seguinte fluxo:

1. Dê um assign para o teu usuário na issue
2. Acrescente a label "in-progress" e outras labels pertinentes (bug, high-priority, discussion)
3. Atribua a issue ao milestone atual
4. Resolva a issue
5. Feche a issue
6. Após fechar a issue, remove a label "in-progress" e mantenha as demais labels

Thanks!!! :heart:
