### ISSUE TITLE
Erro ao dar CTRL+C

### ISSUE THREAD

**Issue by AlissonSteffens** [UNIVALI-LITE/Portugol-Studio#346]
> Esta issue foi gerada automaticamente
```
br.univali.ps.nucleo.ExcecaoAplicacao: java.lang.NullPointerException
	at br.univali.ps.nucleo.TratadorExcecoes.uncaughtException(TratadorExcecoes.java:167)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.awt.EventDispatchThread.processException(EventDispatchThread.java:223)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:215)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NullPointerException
	at sun.awt.datatransfer.DataTransferer$RMI.isRemote(DataTransferer.java:3019)
	at sun.awt.datatransfer.DataTransferer.isRemote(DataTransferer.java:443)
	at java.awt.datatransfer.DataFlavor.isRepresentationClassRemote(DataFlavor.java:1271)
	at sun.awt.datatransfer.DataTransferer.translateTransferable(DataTransferer.java:1333)
	at sun.awt.windows.WDataTransferer.translateTransferable(WDataTransferer.java:219)
	at sun.awt.windows.WClipboard.setContentsNative(WClipboard.java:83)
	at sun.awt.datatransfer.SunClipboard.setContents(SunClipboard.java:106)
	at javax.swing.TransferHandler.exportToClipboard(TransferHandler.java:787)
	at javax.swing.TransferHandler$TransferAction.actionPerformedImpl(TransferHandler.java:1753)
	at javax.swing.TransferHandler$TransferAction.access$800(TransferHandler.java:1692)
	at javax.swing.TransferHandler$TransferAction$1.run(TransferHandler.java:1715)
	at javax.swing.TransferHandler$TransferAction$1.run(TransferHandler.java:1713)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at javax.swing.TransferHandler$TransferAction$2.run(TransferHandler.java:1730)
	at javax.swing.TransferHandler$TransferAction$2.run(TransferHandler.java:1728)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at javax.swing.TransferHandler$TransferAction.actionPerformed(TransferHandler.java:1727)
	at javax.swing.text.JTextComponent.invokeAction(JTextComponent.java:1462)
	at javax.swing.text.JTextComponent.copy(JTextComponent.java:1423)
	at org.fife.ui.rtextarea.RTextAreaEditorKit$CopyAction.actionPerformedImpl(RTextAreaEditorKit.java:679)
	at org.fife.ui.rtextarea.RecordableTextAction.actionPerformed(RecordableTextAction.java:105)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1663)
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2882)
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2929)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2845)
	at java.awt.Component.processEvent(Component.java:6310)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
	at java.awt.Component.dispatchEventImpl(Component.java:4760)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	... 5 more
```

**Comment by noschang** [comment]
Este erro com certeza está ligado à minimização do JDK. Foram removidas classes relacionadas ao pacote RMI. Não deveria dar erro, porque Java RMI é para invocação de código remotamente e a princípio não tem nada a ver com o Swing.

Mas, estou vendo que isso pode ser um tiro que vai sair pela culatra, pois nunca dá pra prever onde as classes são utilizadas. Vou ajustar o processo de build para remover do JDK somente os arquivos indicados no tutorial da Oracle e manter as classes do "rt.jar".
