### ISSUE TITLE
Mensagens de erro do usuário agora são capturadas como erro desconhecido

### ISSUE THREAD

**Issue by sophiacastro** [UNIVALI-LITE/Portugol-Studio#352]
br.univali.ps.nucleo.ExcecaoAplicacao: java.lang.IllegalArgumentException: Acesso negado ao arquivo. Voc￪ n￣o possu￭ permiss￣o de leitura para esse arquivo
	at br.univali.ps.nucleo.TratadorExcecoes.transformarExcecao(TratadorExcecoes.java:228)
	at br.univali.ps.nucleo.TratadorExcecoes.exibirExcecao(TratadorExcecoes.java:55)
	at br.univali.ps.ui.telas.TelaPrincipal.lambda$abrirArquivosCodigoFonte$0(TelaPrincipal.java:288)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.IllegalArgumentException: Acesso negado ao arquivo. Voc￪ n￣o possu￭ permiss￣o de leitura para esse arquivo
	at br.univali.ps.ui.utils.FileHandle.open(FileHandle.java:58)
	at br.univali.ps.ui.telas.TelaPrincipal.lambda$abrirArquivosCodigoFonte$0(TelaPrincipal.java:271)
	... 14 more

**Comment by AdsonEsteves** [comment]
Mensagens como essa de não possuir permissão de leitura, estão sendo capturadas como erro desconhecido também. Tem que se separar esses tipos.

@sophiacastro 
Você não tinha permissão de leitura para o arquivo, então o arquivo estava aberto em outro editor, ou era de algum outro usuário que impediu a leitura
