### ISSUE TITLE
Erro nuat br.univali.ps.ui.utils.FileHandle.save(FileHandle.java:34) 	at br.univali.ps.ui.utils.FileHandle.save(FileHandle.java:13) 	at br.univali.ps.ui.abas.AbaCodigoFonte.salvaArquivoRecuperavel(AbaCodigoFonte.java:889) 	... 23 moremero xxx

### ISSUE THREAD

**Issue by zackDsouza** [UNIVALI-LITE/Portugol-Studio#397]
at br.univali.ps.ui.utils.FileHandle.save(FileHandle.java:34)
	at br.univali.ps.ui.utils.FileHandle.save(FileHandle.java:13)
	at br.univali.ps.ui.abas.AbaCodigoFonte.salvaArquivoRecuperavel(AbaCodigoFonte.java:889)
	... 23 more

**Comment by AdsonEsteves** [comment]
Duplicate of #270

**Comment by AdsonEsteves** [comment]
Esse problema já foi resolvido e em breve será lançada uma nova versão corrigida.
