### ISSUE TITLE
Erro numero xxx

### ISSUE THREAD

**Issue by Kraysh** [UNIVALI-LITE/Portugol-Studio#417]
br.univali.ps.nucleo.ExcecaoAplicacao: java.lang.NullPointerException
	at br.univali.ps.nucleo.TratadorExcecoes.uncaughtException(TratadorExcecoes.java:168)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.awt.EventDispatchThread.processException(EventDispatchThread.java:223)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:215)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NullPointerException
	at org.fife.ui.rsyntaxtextarea.ParserManager.noticeContainsPosition(ParserManager.java:531)
	at org.fife.ui.rsyntaxtextarea.ParserManager.getToolTipText(ParserManager.java:441)
	at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.getToolTipTextImpl(RSyntaxTextArea.java:1741)
	at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.getToolTipText(RSyntaxTextArea.java:1724)
	at javax.swing.ToolTipManager$insideTimerAction.actionPerformed(ToolTipManager.java:663)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	... 5 more

Após aparecer este erro o Portugol começa a mostrar 
os códigos varias vezes e fica impossível de ver o que está sendo digitado.

![screenshot_2](https://user-images.githubusercontent.com/31409782/31999112-f09dc610-b970-11e7-8b99-85fc9f5181c2.png)

**Comment by AdsonEsteves** [comment]
@Kraysh 

Sabe dizer se é alguma ação específica que você faz que causa esse erro?
Acontece da mesma maneira que a issue #371 ?

Podes também dizer as especificações do seu sistema?
ex:
```Windows 10 Education
Versão: 1703
Build: 15063.608
Processador: AMD FX-8300
8Gb Ram
Vídeo: GTX 1050 Ti 4gb
Resolução da tela: 2560x1080

**Comment by Kraysh** [comment]
Realmente é semelhante a issue #371 porém ao digitar " ou ! as coisas começam a se duplicar.

Edição: Windows 10 Pro
Versão: 1703
Build: 15063.674
Processador: I7-3770
8GB ram
Placa de video: GTX 960
Resolução da tela: 1920x1080

**Comment by AdsonEsteves** [comment]
@Kraysh 
Estou fechando essa issue e colocando uma principal (#421) com os possíveis problemas e soluções.
