### ISSUE TITLE
Parser/RSyntax-Tooltip NullPointer

### ISSUE THREAD

**Issue by Aukaii** [UNIVALI-LITE/Portugol-Studio#424]
br.univali.ps.nucleo.ExcecaoAplicacao: java.lang.NullPointerException
	at br.univali.ps.nucleo.TratadorExcecoes.uncaughtException(TratadorExcecoes.java:168)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.awt.EventDispatchThread.processException(EventDispatchThread.java:223)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:215)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NullPointerException
	at org.fife.ui.rsyntaxtextarea.ParserManager.noticeContainsPosition(ParserManager.java:531)
	at org.fife.ui.rsyntaxtextarea.ParserManager.getToolTipText(ParserManager.java:441)
	at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.getToolTipTextImpl(RSyntaxTextArea.java:1741)
	at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.getToolTipText(RSyntaxTextArea.java:1724)
	at javax.swing.ToolTipManager$insideTimerAction.actionPerformed(ToolTipManager.java:663)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	... 5 more

**Comment by AdsonEsteves** [comment]
@Aukaii 

Pode nos dizer se o problema tem algo a ver com a issue #421 ?

Se não, pode nos dizer como ele ocorreu mais ou menos e qual sua versão?

**Comment by Aukaii** [comment]
Creio que nao tem a ver com a issue #421.
Ocorreu quando eu esava tentando compilar um programa feito de uma lista de exercício da minha faculdade, minha versão é a mais atualizada, JDK atualizado também. Ocorreu uma vez só caso ocorra de novo aviso por aqui

**Comment by Aukaii** [comment]
@AdsonEsteves 
Estava escrevendo outro programa aqui quando me deparei com este outro erro, ele apareceu quando eu estava apagando uma linha do desvio condicional de "escolha- caso"


br.univali.ps.nucleo.ExcecaoAplicacao: java.lang.NullPointerException
	at br.univali.ps.nucleo.TratadorExcecoes.uncaughtException(TratadorExcecoes.java:168)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.awt.EventDispatchThread.processException(EventDispatchThread.java:223)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:215)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NullPointerException
	at org.fife.ui.rsyntaxtextarea.ParserManager.noticeContainsPosition(ParserManager.java:531)
	at org.fife.ui.rsyntaxtextarea.ParserManager.getToolTipText(ParserManager.java:441)
	at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.getToolTipTextImpl(RSyntaxTextArea.java:1741)
	at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.getToolTipText(RSyntaxTextArea.java:1724)
	at javax.swing.ToolTipManager$insideTimerAction.actionPerformed(ToolTipManager.java:663)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	... 5 more

**Comment by AdsonEsteves** [comment]
@Aukaii 

Esse erro aconteceu só uma vez denovo? Pode nos passar o código que deu o erro pra tentarmos reproduzi-lo aqui?

Sei que pode ser chato, mas se conseguir achar um padrão tipo "se fizer isso, com certeza acontece", já pode nos ajudar a reproduzir o erro aqui e resolve-lo assim que possível.

**Comment by AdsonEsteves** [comment]
Okay, achei uma possível Issue parecida que foi reportada no repositório do RSyntaxTextArea, que aparentemente foi resolvida ano passado. Ou seja, já deve estar resolvida na ultima versão do RSyntax, mas o Portugol atualmente está com a versão 2.5.4 de 2014 do RSyntax, que ainda tinha esse erro.
Provavelmente atualizando o RSyntax, esse erro pare de acontecer.

https://github.com/bobbylight/RSyntaxTextArea/issues/172

**Comment by AdsonEsteves** [comment]
@Aukaii 

Atualizei o RSyntax e na próxima versão provavelmente não irá mais acontecer, esse tipo de erro.
Está planejado pra uma próxima versão sair dia 10, então fique ligado
