### ISSUE TITLE
Component must be showing on the screen to determine its location

### ISSUE THREAD

**Issue by GilsonLSB** [UNIVALI-LITE/Portugol-Studio#425]
br.univali.ps.nucleo.ExcecaoAplicacao: java.awt.IllegalComponentStateException: component must be showing on the screen to determine its location
	at br.univali.ps.nucleo.TratadorExcecoes.uncaughtException(TratadorExcecoes.java:168)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.awt.EventDispatchThread.processException(EventDispatchThread.java:223)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:215)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.awt.IllegalComponentStateException: component must be showing on the screen to determine its location
	at java.awt.Component.getLocationOnScreen_NoTreeLock(Component.java:2062)
	at java.awt.Component.getLocationOnScreen(Component.java:2036)
	at javax.swing.text.JTextComponent$InputMethodRequestsHandler.getTextLocation(JTextComponent.java:4643)
	at sun.awt.im.InputMethodContext.getTextLocation(InputMethodContext.java:278)
	at sun.awt.windows.WInputMethod$1.run(WInputMethod.java:588)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	... 5 more

**Comment by AdsonEsteves** [comment]
@GilsonLSB 

Pode nos dizer que versão está usando e como esse erro ocorreu mais ou menos?

**Comment by GilsonLSB** [comment]
Versão utilizada 2.6.3
O erro ocorreu quando abri um arquivo do portugol studio (.por)

**Comment by AdsonEsteves** [comment]
Aparentemente este erro é da própria JDK:

https://bugs.openjdk.java.net/browse/JDK-8179665

E este problema foi resolvido na versão 9 da JDK, que ainda não foi lançada. De acordo com a issue, este erro se capturado, pode ser ignorado pois não causa maiores problemas.
Então até ser lançada a nova JDK, a melhor maneira é ignorar o erro, quando for capturado.
Vamos resolver isso para a próxima versão.

**Comment by lukeu** [comment]
FYI: this crash has now been fixed in JDK 8u152 also, as can be seen here:

  https://bugs.java.com/view_bug.do?bug_id=8179665
  https://bugs.openjdk.java.net/browse/JDK-8193383

**Comment by noschang** [comment]
Hi @lukeu.
Thanks for your help.

However we're not using OpenJDK, We're using the official JDK 8 from Oracle shipped with the application.

Do you know if this bug occurs with the Oracle version?
