### ISSUE TITLE
Mensagem de Erro semantico em soma direta no NoPara

### ISSUE THREAD

**Issue by jeffyuri7** [UNIVALI-LITE/Portugol-Studio#440]
>O erro foi gerado no laço de repetição para. Eu mudei a sintaxe na intenção de poder manipular o incremento automático. Minha intenção era que o incremento desse um salto de dois em dois, em vez de um em um. Por isso usei a seguinte sintaxe, alterando um exemplo que o próprio programa tem. Gostaria de saber se há previsão de modificar esse incremento de outra forma, assim como há no VisualG.

programa
{
    funcao inicio()
    {
		inteiro tab

		para (inteiro c=1; c<=10; **c+2**)
		{
			tab=c*3
			escreva ("3 x ", c, " = ", tab, "\n")
		}
	}
}

> Esta issue foi gerada automaticamente

br.univali.ps.nucleo.ExcecaoAplicacao: java.util.concurrent.ExecutionException: java.lang.ClassCastException: br.univali.portugol.nucleo.asa.NoOperacaoSoma cannot be cast to br.univali.portugol.nucleo.asa.NoOperacaoAtribuicao
	at br.univali.ps.nucleo.TratadorExcecoes.transformarExcecao(TratadorExcecoes.java:220)
	at br.univali.ps.nucleo.TratadorExcecoes.exibirExcecao(TratadorExcecoes.java:41)
	at br.univali.ps.ui.abas.AbaCodigoFonte$AcaoExecucao.actionPerformed(AbaCodigoFonte.java:1003)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.util.concurrent.ExecutionException: java.lang.ClassCastException: br.univali.portugol.nucleo.asa.NoOperacaoSoma cannot be cast to br.univali.portugol.nucleo.asa.NoOperacaoAtribuicao
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at br.univali.ps.ui.abas.AbaCodigoFonte$AcaoExecucao.actionPerformed(AbaCodigoFonte.java:991)
	... 40 more
Caused by: java.lang.ClassCastException: br.univali.portugol.nucleo.asa.NoOperacaoSoma cannot be cast to br.univali.portugol.nucleo.asa.NoOperacaoAtribuicao
	at br.univali.portugol.nucleo.execucao.gerador.GeradorCodigoJava$VisitorGeracaoCodigo.geraCodigoInspecao(GeradorCodigoJava.java:707)
	at br.univali.portugol.nucleo.execucao.gerador.GeradorCodigoJava$VisitorGeracaoCodigo.visitar(GeradorCodigoJava.java:690)
	at br.univali.portugol.nucleo.execucao.gerador.GeradorCodigoJava$VisitorGeracaoCodigo.visitar(GeradorCodigoJava.java:98)
	at br.univali.portugol.nucleo.asa.NoPara.aceitar(NoPara.java:157)
	at br.univali.portugol.nucleo.execucao.gerador.helpers.Utils.visitarBlocos(Utils.java:285)
	at br.univali.portugol.nucleo.execucao.gerador.helpers.GeradorDeclaracaoMetodo.gera(GeradorDeclaracaoMetodo.java:65)
	at br.univali.portugol.nucleo.execucao.gerador.GeradorCodigoJava$VisitorGeracaoCodigo.geraMetodos(GeradorCodigoJava.java:313)
	at br.univali.portugol.nucleo.execucao.gerador.GeradorCodigoJava.gera(GeradorCodigoJava.java:94)
	at br.univali.portugol.nucleo.Compilador.geraPrograma(Compilador.java:165)
	at br.univali.portugol.nucleo.Compilador.compilar(Compilador.java:106)
	at br.univali.portugol.nucleo.Portugol.compilar(Portugol.java:26)
	at br.univali.portugol.nucleo.Portugol.compilarParaExecucao(Portugol.java:45)
	at br.univali.ps.ui.abas.AbaCodigoFonte.lambda$compilaProgramaParaExecucao$4(AbaCodigoFonte.java:1747)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by AlissonSteffens** [comment]
@jeffyuri7 eremos verificar o erro, porém para acelerar o seu desenvolvimento, eu resolvi já trazer o código da maneira como o Portugol Studio espera;
Para modificar o incremento, basta fazer a seguinte
```
programa
{
	funcao inicio()
	{
		inteiro tab

		para (inteiro c=1; c<=10; c = c+2)
		{
			tab=c*3
			escreva ("3 x ", c, " = ", tab, "\n")
		}
	}
}
```

utilizando **c = c+2**

**Comment by AlissonSteffens** [comment]
Código que gera o erro:
```
programa
{
funcao inicio()
{
inteiro tab

	para (inteiro c=1; c<=10; c+2)
	{
		tab=c*3
		escreva ("3 x ", c, " = ", tab, "\n")
	}
}

}
```
