### ISSUE TITLE
IllegalArgumentException: bad position: 1208

### ISSUE THREAD

**Issue by Tatyorn** [UNIVALI-LITE/Portugol-Studio#454]
br.univali.ps.nucleo.ExcecaoAplicacao: java.lang.IllegalArgumentException: bad position: 1208
	at br.univali.ps.nucleo.TratadorExcecoes.transformarExcecao(TratadorExcecoes.java:220)
	at br.univali.ps.nucleo.TratadorExcecoes.exibirExcecao(TratadorExcecoes.java:41)
	at br.univali.ps.ui.telas.TelaPrincipal.lambda$abrirArquivosCodigoFonte$1(TelaPrincipal.java:273)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.IllegalArgumentException: bad position: 1208
	at javax.swing.text.JTextComponent.setCaretPosition(JTextComponent.java:1629)
	at br.univali.ps.ui.editor.Editor.carregarPosicaoCursor(Editor.java:1036)
	at br.univali.ps.ui.editor.Editor.carregarInformacoesPortugolStudio(Editor.java:996)
	at br.univali.ps.ui.editor.Editor.setCodigoFonte(Editor.java:989)
	at br.univali.ps.ui.abas.AbaCodigoFonte.setCodigoFonte(AbaCodigoFonte.java:1326)
	at br.univali.ps.ui.telas.TelaPrincipal.lambda$abrirArquivosCodigoFonte$1(TelaPrincipal.java:266)
	... 14 more

**Comment by Rafaelfcosta** [comment]
@Tatyorn Poderia informar como aconteceu o erro e qual versão do PortugolStudio vc está usando?

**Comment by Tatyorn** [comment]
versão 2.6.4
Apareceu quando eu tentei abrir um arquivo, mas foi só em um dos arquivos. Eu abri um novo modelo e copiei o código(que eu tinha deixado em txt caso essas coisas acontecessem) e funcionou normalmente.
Antes disso, eu tinha instalado o Portugol e ele desapareceu, como se não tivesse instalado. Depois eu fixei ele na barra de tarefas, mas toda vez que eu reinicio o notebook, ele desaparece da barra.
________________________________
De: Rafael <notifications@github.com>
Enviado: quarta-feira, 6 de dezembro de 2017 13:53
Para: UNIVALI-LITE/Portugol-Studio
Cc: Tatyorn; Mention
Assunto: Re: [UNIVALI-LITE/Portugol-Studio] Erro numero xxx (#454)


@Tatyorn<https://github.com/tatyorn> Poderia informar como aconteceu o erro e qual versão do PortugolStudio vc está usando?

**Comment by noschang** [comment]
@AdsonEsteves. Meu palpite é que ele tenha tentado abrir um arquivo mais antigo em uma versão mais nova do Portugol Studio.

Lembra que a gente processa alguns metadados que estão no final do arquivo (posição do cursor, pontos de parada, etc)? Em alguns arquivos mais antigos, alguns destes metadados não estão presentes e pode esta dando problema ao tentar abrí-los,

@Tatyorn, você poderia por favor nos informar qual a versão do Portugol Studio que você está usando? Além disso, seria muito importante que você postasse aqui no Github o arquivo que você tentou abrir (se você ainda tiver ele).

@Tatyorn, quanto ao problema de o ícon estar desaparecendo da barra de tarefas, pediria que você [abrisse uma nova issue](https://github.com/UNIVALI-LITE/Portugol-Studio/issues/new) relatando o problema. Se possível, coloque capturas de tela e informe a versão do Windows que você está utilizando para que possamos testar.

**Comment by AdsonEsteves** [comment]
@noschang 

Testei tirando os metadados do arquivo, como também alterando as variáveis, e nenhum dos dois casos gerou o erro.

**Comment by AdsonEsteves** [comment]
Actually, agora consegui refazer o erro.

Quando o metadado "POSIÇÃO-CURSOR" ultrapassa o número de linhas/colunas disponíveis no arquivo, acaba gerando este erro.
