### ISSUE TITLE
Erro numero xxx

### ISSUE THREAD

**Issue by Mateus-Hirt** [UNIVALI-LITE/Portugol-Studio#471]
**Achei um erro :dog2:**

br.univali.ps.nucleo.ExcecaoAplicacao: java.awt.IllegalComponentStateException: component must be showing on the screen to determine its location
	at br.univali.ps.nucleo.TratadorExcecoes.uncaughtException(TratadorExcecoes.java:157)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.awt.EventDispatchThread.processException(EventDispatchThread.java:223)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:215)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.awt.IllegalComponentStateException: component must be showing on the screen to determine its location
	at java.awt.Component.getLocationOnScreen_NoTreeLock(Component.java:2062)
	at java.awt.Component.getLocationOnScreen(Component.java:2036)
	at javax.swing.text.JTextComponent$InputMethodRequestsHandler.getTextLocation(JTextComponent.java:4643)
	at sun.awt.im.InputMethodContext.getTextLocation(InputMethodContext.java:278)
	at sun.awt.windows.WInputMethod$1.run(WInputMethod.java:588)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	... 5 more

**Comment by AdsonEsteves** [comment]
@Mateus-Hirt 

Qual versão do Portugol Studio você está usando?

**Comment by Mateus-Hirt** [comment]
2.6.4, pois, por algum motivo, a versão 2.6.5 não quer baixar no meu computador...

**Comment by AdsonEsteves** [comment]
@Mateus-Hirt 
Ah sim, esse erro foi relatado(#425) e corrigido na nova versão

O instalador simplesmente não baixa no site? Isso acontece com qual navegador? Já tentou outro ou em outro pc?

**Comment by AdsonEsteves** [comment]
Duplicate of #425

**Comment by Mateus-Hirt** [comment]
@AdsonEsteves Acontece com o Chrome... E eu já tentei baixar no Firefox, e em um notebook, e aconteceu o mesmo, não baixa.

Deve ser algo da minha máquina, pois aconteceu o mesmo quando tentei baixar a versão 2.6.4...

**Comment by AdsonEsteves** [comment]
@Mateus-Hirt 
Você tentou em outra máquina e não deu certo também? E isso só acontece com a gente certo?

Okay, tente primeiro com o release direto no github https://github.com/UNIVALI-LITE/Portugol-Studio/releases/tag/v2.6.5

Se não der certo, sugiro tentar um gerenciador de download de sua preferencia, copiar o link de download e baixar por ele.
