### ISSUE TITLE
:bug: Mensagem de erro JAVA no console ao usar Graficos.renderizar()

### ISSUE THREAD

**Issue by rytix** [UNIVALI-LITE/Portugol-Studio#476]
**Descrição do Problema**:
Uma mensagem de erro java nada amigável aparece ao tentar usar a função renderizar da biblioteca gráficos.

Recomendo colocar uma mensagem que avisa ao usuário que ele precisa estar com o modo gráfico ativado para usar esta função.
**Mensagem de Erro (se houver)**:

Ocorreu um erro durante a execução do programa: java.lang.NullPointerException
	at br.univali.portugol.nucleo.bibliotecas.graficos.SuperficieDesenhoImpl.renderizar(SuperficieDesenhoImpl.java:78)
	at br.univali.portugol.nucleo.bibliotecas.Graficos.renderizar(Graficos.java:284)
	at programas.Programa1517859218726.executar(Programa1517859218726.java:27)
	at br.univali.portugol.nucleo.programa.TarefaExecucao.run(TarefaExecucao.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Linha: 9, Coluna: 2

**Captura de Tela / Arquivo.por**:
![image](https://user-images.githubusercontent.com/7809511/35824713-e5f6e5c2-0a9a-11e8-80e8-d00add6d9db3.png)

**Comment by AdsonEsteves** [comment]
fixed in ef72dbed5ff0409082b6e9f4769dfdd9d42f10db
