### ISSUE TITLE
Problema de permissão ao salvar arquivo no OS X Yosemite versão 10.10.5.

### ISSUE THREAD

**Issue by EvaldoGomes** [UNIVALI-LITE/Portugol-Studio#483]
br.univali.ps.nucleo.ExcecaoAplicacao: java.lang.NullPointerException
	at br.univali.ps.nucleo.TratadorExcecoes.transformarExcecao(TratadorExcecoes.java:220)
	at br.univali.ps.nucleo.TratadorExcecoes.exibirExcecao(TratadorExcecoes.java:41)
	at br.univali.ps.ui.abas.AbaCodigoFonte.salvaArquivo(AbaCodigoFonte.java:848)
	at br.univali.ps.ui.abas.AbaCodigoFonte.lambda$configurarArvoreEstrutural$1(AbaCodigoFonte.java:726)
	at br.univali.ps.ui.rstautil.tree.filters.PortugolASTFilter.fireFilterChanged(PortugolASTFilter.java:50)
	at br.univali.ps.ui.rstautil.tree.filters.PortugolASTFilter.access$100(PortugolASTFilter.java:11)
	at br.univali.ps.ui.rstautil.tree.filters.PortugolASTFilter$ChangeListener.symbolTypeRejected(PortugolASTFilter.java:158)
	at br.univali.ps.ui.rstautil.tree.filters.SymbolTypeFilter.fireSymbolTypeRejected(SymbolTypeFilter.java:118)
	at br.univali.ps.ui.rstautil.tree.filters.SymbolTypeFilter.reject(SymbolTypeFilter.java:200)
	at br.univali.ps.ui.rstautil.tree.filters.view.SymbolTypeFilterView.toggleSymbolType(SymbolTypeFilterView.java:128)
	at br.univali.ps.ui.rstautil.tree.filters.view.SymbolTypeFilterView.updateFilter(SymbolTypeFilterView.java:99)
	at br.univali.ps.ui.rstautil.tree.filters.view.SymbolTypeFilterView.buttonVariablesActionPerformed(SymbolTypeFilterView.java:370)
	at br.univali.ps.ui.rstautil.tree.filters.view.SymbolTypeFilterView.access$800(SymbolTypeFilterView.java:21)
	at br.univali.ps.ui.rstautil.tree.filters.view.SymbolTypeFilterView$7.actionPerformed(SymbolTypeFilterView.java:315)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:308)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NullPointerException
	at br.univali.ps.ui.utils.FileHandle.save(FileHandle.java:36)
	at br.univali.ps.ui.utils.FileHandle.save(FileHandle.java:14)
	at br.univali.ps.ui.abas.AbaCodigoFonte.salvaArquivo(AbaCodigoFonte.java:838)
	... 50 more

**Comment by AdsonEsteves** [comment]
@EvaldoGomes 

Não tenho certeza se fechou por já ter resolvido, mas de qualquer maneira.
Qual versão do Portugol Studio você está usando? Já tivemos esse erro anteriormente, e foi resolvido nas novas versões.

I'm not sure if you close because you already resolved it, but anyway.
What Portugol Studio version are you using? We already had this error before, but in the lastest version its already resolved.

**Comment by EvaldoGomes** [comment]
Bom dia!

Estou usando v2.6.5, deixando claro que não conheço a ferramenta... e estou
começando a estudar programação agora!

Não sei foi no instalar do Portugol Studio que foi mal feito e por isso
aparece o erro agora!

Quando vou executar o programa que estou aprendendo a desenvolver não roda
e aparece um erro no java no console e não mostra o resultado das
variáveis, envio um print do erro!

Por favor me ajuda a solucionar preciso desta ferramenta para continuar com
o aprendizado, lembrando que, a dificuldade de encontrar ferramentas open
sourcer que roda em OS é imensa.


[image: Imagem inline 1]

Grato,

Evaldo

2018-02-14 2:57 GMT-02:00 Adsu <notifications@github.com>:

**Comment by AdsonEsteves** [comment]
@EvaldoGomes 

Então está usando um Mac? Realmente é complicado isso, atualmente estamos com alguns problemas realmente nessas versões, visto que, não temos um mac de verdade aqui e usamos máquinas virtuais nesse caso.

Vou pedir que tente isso:
1. Entre no terminal e escreva "sudo chmod -R go+x /Applications/Portugol\ Studio.app/Contents/" sem aspas

2. Execute o Portugol pelo terminal "sudo /Applications/Portugol\ Studio.app/Contents/Resources/IDE/executar-studio-mac.command" sem aspas

E também nos passe qual versão do mac estás usando.

**Comment by EvaldoGomes** [comment]
Olá, 
Meu mac roda sistema OS X Yosemite versão 10.10.5.

Grato,

Evaldo Gomes

**Comment by EvaldoGomes** [comment]
Resolvido!!!

Amigo, entrei pelo terminal e executei o script indicado e ficou tudo maravilha!!

Grato,
Evaldo Gomes

**Comment by AdsonEsteves** [comment]
@EvaldoGomes 

Ótimo, pelo menos sabemos o problema. Infelizmente por hora vai ter que usar assim até resolvermos e não precisar fazer esse processo.

Vou deixar a issue aberta já que isso ainda é um problema que precisamos resolver.

**Comment by AdsonEsteves** [comment]
Movido para #520
