### ISSUE TITLE
Erro de divisão por zero ao no meio da execução do programa arrastar um componente para a zona de variaveis...

### ISSUE THREAD

**Issue by rytix** [UNIVALI-LITE/Portugol-Studio#488]
Como reproduzir:

Crie uma variável no meio do programa
mantenha shift + f6 pressionado
enquanto pressionado shift + f6 use o mouse para arrastar a variável para a zona de variáveis

Não é um erro ao arrastar variáveis e sim ao tentar selecionar texto enquanto o portugol está executando

![image](https://user-images.githubusercontent.com/7809511/36860474-1bccd49a-1d60-11e8-81c4-c9b884f67e8c.png)

> Esta issue foi gerada automaticamente

br.univali.ps.nucleo.ExcecaoAplicacao: java.lang.ArithmeticException: / by zero
	at br.univali.ps.nucleo.TratadorExcecoes.uncaughtException(TratadorExcecoes.java:157)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.awt.EventDispatchThread.processException(EventDispatchThread.java:223)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:215)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ArithmeticException: / by zero
	at org.fife.ui.rsyntaxtextarea.SyntaxView.viewToModel(SyntaxView.java:938)
	at javax.swing.plaf.basic.BasicTextUI$RootView.viewToModel(BasicTextUI.java:1552)
	at javax.swing.plaf.basic.BasicTextUI.viewToModel(BasicTextUI.java:1101)
	at javax.swing.plaf.basic.BasicTextUI.viewToModel(BasicTextUI.java:1074)
	at javax.swing.text.JTextComponent.viewToModel(JTextComponent.java:1395)
	at org.fife.ui.rsyntaxtextarea.ParserManager.getToolTipText(ParserManager.java:421)
	at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.getToolTipTextImpl(RSyntaxTextArea.java:1741)
	at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.getToolTipText(RSyntaxTextArea.java:1724)
	at javax.swing.ToolTipManager.mouseMoved(ToolTipManager.java:599)
	at java.awt.AWTEventMulticaster.mouseMoved(AWTEventMulticaster.java:330)
	at java.awt.Component.processMouseMotionEvent(Component.java:6578)
	at javax.swing.JComponent.processMouseMotionEvent(JComponent.java:3342)
	at java.awt.Component.processEvent(Component.java:6302)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4539)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	... 5 more

[pressione o botao "copiar erro" no Portugol Studio e cole o erro aqui antes de enviar]

**Comment by AdsonEsteves** [comment]
ignored here ab8c33b2aa1928103c29af60e0392d71443c41ac
