### ISSUE TITLE
Erro numero df2fdde99fd7138354a3708371c022857fa6ab4b v2.6.7

### ISSUE THREAD

**Issue by pauloantonelli** [UNIVALI-LITE/Portugol-Studio#530]
> Esta issue foi gerada automaticamente
br.univali.ps.nucleo.ExcecaoAplicacao: java.lang.NullPointerException
	at br.univali.ps.nucleo.TratadorExcecoes.uncaughtException(TratadorExcecoes.java:126)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.awt.EventDispatchThread.processException(EventDispatchThread.java:223)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:215)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NullPointerException
	at com.alee.managers.tooltip.WebCustomTooltip.getActualDisplayWay(WebCustomTooltip.java:413)
	at com.alee.managers.tooltip.WebCustomTooltip.paintComponent(WebCustomTooltip.java:1050)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5158)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4969)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:831)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	... 5 more

**Comment by AlissonSteffens** [comment]
@pauloantonelli sabe dizer como o ero ocorreu (o que estavas fazendo)

**Comment by pauloantonelli** [comment]
Oi allison entao eu estava codificando e estava aberto em torno de 7 projetos pequenos, e dai quando tentei salvar o projeto atual deu o erro e nao salvou


Att. Paulo Antonelli

-------- Mensagem original --------
De : Alisson Steffens
Data:12/04/2018 13h30 (GMT-03:00)
Para: UNIVALI-LITE/Portugol-Studio
Cc: pauloantonelli ,Mention
Assunto: Re: [UNIVALI-LITE/Portugol-Studio] Erro numero df2fdde99fd7138354a3708371c022857fa6ab4b v2.6.7 (#530)

@pauloantonelli<https://github.com/pauloantonelli> sabe dizer como o ero ocorreu (o que estavas fazendo)

**Comment by AdsonEsteves** [comment]
corrigido em  b2c1669
