### ISSUE TITLE
Erro RSyntaxUtilities.getMatchingBracketPosition numero a43482291e6e08af114a6a53fcc5eabbb8bab0d3 v2.6.9

### ISSUE THREAD

**Issue by M3GUST4** [UNIVALI-LITE/Portugol-Studio#564]
br.univali.ps.nucleo.ExcecaoAplicacao: java.lang.NullPointerException
	at br.univali.ps.nucleo.TratadorExcecoes.uncaughtException(TratadorExcecoes.java:126)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.awt.EventDispatchThread.processException(EventDispatchThread.java:223)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:215)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NullPointerException
	at org.fife.ui.rsyntaxtextarea.RSyntaxUtilities.getMatchingBracketPosition(RSyntaxUtilities.java:461)
	at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.doBracketMatching(RSyntaxTextArea.java:761)
	at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.fireCaretUpdate(RSyntaxTextArea.java:807)
	at org.fife.ui.rtextarea.RTextArea$RTextAreaMutableCaretEvent.mousePressed(RTextArea.java:1680)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.Component.processMouseEvent(Component.java:6530)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4523)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	... 5 more

**Comment by AdsonEsteves** [comment]
@M3GUST4 

Pode nos dizer como ocorreu este erro?

**Comment by M3GUST4** [comment]
Ocorreu depois que cliquei duas vezes com o botão do meio do mouse justo na hora em que eu estava digitando um código, e o click com o botão do meio do mouse na aba de programação do portugol funcionou como um ctrl + v, aí apaguei o conteúdo que foi colado no programa e começou a dar este erro. Tive que fechar o Portugol Studio e abri-lo novamente para poder utilizar o mesmo.


________________________________
De: Adsu <notifications@github.com>
Enviado: segunda-feira, 21 de maio de 2018 17:35
Para: UNIVALI-LITE/Portugol-Studio
Cc: M3GUST4; Mention
Assunto: Re: [UNIVALI-LITE/Portugol-Studio] Erro numero a43482291e6e08af114a6a53fcc5eabbb8bab0d3 v2.6.9 (#564)


@M3GUST4<https://github.com/M3GUST4>

Pode nos dizer como ocorreu este erro?

**Comment by AdsonEsteves** [comment]
Sem reportes deste erro desde as novas versões
