### ISSUE TITLE
Erro ProvedorConclusaoCodigoPrograma.conclusaoNoEscopoCursor numero 82aec8a82bd63713f1d1f950342c194c914710a9 v2.6.9

### ISSUE THREAD

**Issue by Mateus-Hirt** [UNIVALI-LITE/Portugol-Studio#605]
br.univali.ps.nucleo.ExcecaoAplicacao: java.lang.NullPointerException
	at br.univali.ps.nucleo.TratadorExcecoes.uncaughtException(TratadorExcecoes.java:126)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.awt.EventDispatchThread.processException(EventDispatchThread.java:223)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:215)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NullPointerException
	at br.univali.ps.ui.rstautil.completion.ProvedorConclusaoCodigoPrograma.conclusaoNoEscopoCursor(ProvedorConclusaoCodigoPrograma.java:492)
	at br.univali.ps.ui.rstautil.completion.ProvedorConclusaoCodigoPrograma.getCompletions(ProvedorConclusaoCodigoPrograma.java:82)
	at br.univali.ps.ui.rstautil.completion.ProvedorConclusaoCodigoPortugol.getCompletionsImpl(ProvedorConclusaoCodigoPortugol.java:98)
	at org.fife.ui.autocomplete.CompletionProviderBase.getCompletions(CompletionProviderBase.java:104)
	at org.fife.ui.autocomplete.AutoCompletion.refreshPopupWindow(AutoCompletion.java:801)
	at br.univali.ps.ui.editor.PSAutoCompletion.refreshPopupWindow(PSAutoCompletion.java:92)
	at org.fife.ui.autocomplete.AutoCompletion.doCompletion(AutoCompletion.java:287)
	at org.fife.ui.autocomplete.AutoCompletion$AutoActivationListener.actionPerformed(AutoCompletion.java:1279)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	... 5 more

**Comment by AdsonEsteves** [comment]
@Mateus-Hirt 

Esse erro sempre ocorre ou é com um código específico?
Pode postar ele?

**Comment by AdsonEsteves** [comment]
Sem reportes deste erro desde as novas versões
