### ISSUE TITLE
Erro numero xxx

### ISSUE THREAD

**Issue by Lucas0901** [UNIVALI-LITE/Portugol-Studio#618]
> Esta issue foi gerada automaticamente
br.univali.ps.nucleo.ExcecaoAplicacao: java.lang.NullPointerException
	at br.univali.ps.nucleo.TratadorExcecoes.transformarExcecao(TratadorExcecoes.java:228)
	at br.univali.ps.nucleo.TratadorExcecoes.exibirExcecao(TratadorExcecoes.java:55)
	at br.univali.ps.ui.abas.AbaCodigoFonte.salvaArquivoRecuperavel(AbaCodigoFonte.java:897)
	at br.univali.ps.ui.abas.AbaCodigoFonte.access$2800(AbaCodigoFonte.java:92)
	at br.univali.ps.ui.abas.AbaCodigoFonte$19.propertyChange(AbaCodigoFonte.java:1127)
	at java.beans.PropertyChangeSupport.fire(Unknown Source)
	at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at br.univali.ps.ui.rstautil.PortugolParser.parse(PortugolParser.java:196)
	at org.fife.ui.rsyntaxtextarea.ParserManager.actionPerformed(ParserManager.java:157)
	at javax.swing.Timer.fireActionPerformed(Unknown Source)
	at javax.swing.Timer$DoPostEvent.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at br.univali.ps.ui.utils.FileHandle.save(FileHandle.java:34)
	at br.univali.ps.ui.utils.FileHandle.save(FileHandle.java:13)
	at br.univali.ps.ui.abas.AbaCodigoFonte.salvaArquivoRecuperavel(AbaCodigoFonte.java:889)
	... 23 more

**Comment by AdsonEsteves** [comment]
@Lucas0901 

Por favor atualize o Portugol para a nova versão isto já foi corrigido
