### ISSUE TITLE
Erro em executar algoritmo 

### ISSUE THREAD

**Issue by JosueBras** [UNIVALI-LITE/Portugol-Studio#621]
> Esta issue foi gerada automaticamente

br.univali.ps.nucleo.ExcecaoAplicacao: java.lang.NullPointerException: peer
	at br.univali.ps.nucleo.TratadorExcecoes.uncaughtException(TratadorExcecoes.java:157)
	at java.lang.ThreadGroup.uncaughtException(Unknown Source)
	at java.lang.ThreadGroup.uncaughtException(Unknown Source)
	at java.awt.EventDispatchThread.processException(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.WaitDispatchSupport$2.run(Unknown Source)
	at java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(Unknown Source)
	at java.awt.Dialog.show(Unknown Source)
	at java.awt.Component.show(Unknown Source)
	at java.awt.Component.setVisible(Unknown Source)
	at java.awt.Window.setVisible(Unknown Source)
	at java.awt.Dialog.setVisible(Unknown Source)
	at br.univali.ps.nucleo.TratadorExcecoes.exibirExcecaoDetalhada(TratadorExcecoes.java:105)
	at br.univali.ps.nucleo.TratadorExcecoes.exibir(TratadorExcecoes.java:78)
	at br.univali.ps.nucleo.TratadorExcecoes.exibirExcecao(TratadorExcecoes.java:48)
	at br.univali.ps.nucleo.TratadorExcecoes.uncaughtException(TratadorExcecoes.java:157)
	at java.lang.ThreadGroup.uncaughtException(Unknown Source)
	at java.lang.ThreadGroup.uncaughtException(Unknown Source)
	at java.awt.EventDispatchThread.processException(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.NullPointerException: peer
	at sun.awt.windows.WInputMethod.openCandidateWindow(Native Method)
	at sun.awt.windows.WInputMethod.access$400(Unknown Source)
	at sun.awt.windows.WInputMethod$1.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	... 26 more

FAVOR CORRIR O ERRO NO PORTUGOL, TODA VEZ QUE EXECUTAR UM ALGORITMO VEM A MSG DE ERRO UMAS 3 VEZES SEGUIDAS.

Obrigado 👍

**Comment by JosueBras** [comment]
versão 2.6.5


versão utilizadas nos lab 2 e 4 do bloco B6.



________________________________
De: Adsu <notifications@github.com>
Enviado: quarta-feira, 29 de agosto de 2018 23:20
Para: UNIVALI-LITE/Portugol-Studio
Cc: JosueBras; Mention
Assunto: Re: [UNIVALI-LITE/Portugol-Studio] Erro em executar algoritmo (#621)


@JosueBras<https://github.com/JosueBras>

Qual versão do Portugol Studio você está usando?

**Comment by AdsonEsteves** [comment]
@JosueBras 

Esse erro já foi corrigido na versão mais nova do Portugol Studio, se possível peça para atualizarem ele.
