### ISSUE TITLE
Erro Inspetor de simbolos numero bd422939cd794a2c0e6768e1065a455f70b15ea2 v2.6.9

### ISSUE THREAD

**Issue by RedSoldier019** [UNIVALI-LITE/Portugol-Studio#654]
br.univali.ps.nucleo.ExcecaoAplicacao: java.lang.NullPointerException
	at br.univali.ps.nucleo.TratadorExcecoes.uncaughtException(TratadorExcecoes.java:126)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.awt.EventDispatchThread.processException(EventDispatchThread.java:223)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:215)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NullPointerException
	at br.univali.ps.ui.inspetor.InspetorDeSimbolos.adicionaNoVetor(InspetorDeSimbolos.java:542)
	at br.univali.ps.ui.inspetor.InspetorDeSimbolos.adicionaNo(InspetorDeSimbolos.java:682)
	at br.univali.ps.ui.inspetor.InspetorDeSimbolos$TarefaReconstrucaoNosInspecionados.run(InspetorDeSimbolos.java:749)
	at br.univali.ps.ui.inspetor.InspetorDeSimbolos.setPrograma(InspetorDeSimbolos.java:141)
	at br.univali.ps.ui.abas.AbaCodigoFonte$20.propertyChange(AbaCodigoFonte.java:1016)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:328)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at br.univali.ps.ui.rstautil.PortugolParser.parse(PortugolParser.java:196)
	at org.fife.ui.rsyntaxtextarea.ParserManager.actionPerformed(ParserManager.java:157)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	... 5 more

**Comment by AdsonEsteves** [comment]
@RedSoldier019 

Como que aconteceu o erro? Consegue repetir ele?

**Comment by AdsonEsteves** [comment]
Não há indícios do erro nas novas versões.
