### ISSUE TITLE
Erro no Log Manager

### ISSUE THREAD

**Issue by Portugol01** [UNIVALI-LITE/Portugol-Studio#669]
br.univali.ps.nucleo.ExcecaoAplicacao: java.lang.NullPointerException
	at br.univali.ps.nucleo.TratadorExcecoes.uncaughtException(TratadorExcecoes.java:131)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.lang.Thread.dispatchUncaughtException(Thread.java:1959)
Caused by: java.lang.NullPointerException
	at br.univali.ps.nucleo.LogManager$1.run(LogManager.java:57)

**Comment by AdsonEsteves** [comment]
23f64f911cf36870f2f27e6ffe5675978d99cddb
