### ISSUE TITLE
Peer 3907b2ae2e6ae32732a29fd71264b80e2d95612f v2.7.2

### ISSUE THREAD

**Issue by glensouza62** [UNIVALI-LITE/Portugol-Studio#692]
> Esta issue foi gerada automaticamente

[pressione o botao "copiar erro" no Portugol Studio e cole o erro aqui antes de enviar]
br.univali.ps.nucleo.ExcecaoAplicacao: java.lang.NullPointerException: peer
	at br.univali.ps.nucleo.TratadorExcecoes.uncaughtException(TratadorExcecoes.java:131)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.awt.EventDispatchThread.processException(EventDispatchThread.java:227)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:219)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NullPointerException: peer
	at sun.awt.windows.WInputMethod.openCandidateWindow(Native Method)
	at sun.awt.windows.WInputMethod.access$400(WInputMethod.java:45)
	at sun.awt.windows.WInputMethod$1.run(WInputMethod.java:602)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	... 5 more

**Comment by AdsonEsteves** [comment]
@glensouza62 
Pode dizer como ocorreu esse erro? Consegue repetir ele?

**Comment by glensouza62** [comment]
Boa tarde
Quando aperto o executar ele fica parado só no processando e não executa.
Posso mandar por vídeo se ajudar.
Obrigado

Em seg, 29 de abr de 2019 às 15:24, Adsu <notifications@github.com>
escreveu:

**Comment by AdsonEsteves** [comment]
Isso continua acontecendo nas versões recentes?
