### ISSUE TITLE
Erro numero 700ec85c8c1a9adcdcf33ba306eb666b40cd37b1 v2.7.4

### ISSUE THREAD

**Issue by JorgeNachtigall** [UNIVALI-LITE/Portugol-Studio#768]
> Esta issue foi gerada automaticamente

br.univali.ps.nucleo.ExcecaoAplicacao: br.univali.ps.plugins.base.ErroInstalacaoPlugin: Erro ao instalar o plugin 'Plugin-Exemplo.psa'
	at br.univali.ps.nucleo.TratadorExcecoes.transformarExcecao(TratadorExcecoes.java:267)
	at br.univali.ps.nucleo.TratadorExcecoes.exibirExcecao(TratadorExcecoes.java:42)
	at br.univali.ps.plugins.base.GerenciadorPlugins$1.run(GerenciadorPlugins.java:120)
	at java.lang.Thread.run(Thread.java:748)
Caused by: br.univali.ps.plugins.base.ErroInstalacaoPlugin: Erro ao instalar o plugin 'Plugin-Exemplo.psa'
	... 2 more
Caused by: java.io.FileNotFoundException: /Applications/Portugol Studio.app/Contents/Resources/IDE/plugins/Plugin-Exemplo./ExemploPlugin.jar (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at br.univali.ps.ui.utils.UnzipUtility.extractFile(UnzipUtility.java:65)
	at br.univali.ps.ui.utils.UnzipUtility.unzip(UnzipUtility.java:46)
	at br.univali.ps.plugins.base.GerenciadorPlugins$1.run(GerenciadorPlugins.java:118)
	... 1 more

Estou tendo este problema ao tentar criar um plugin para o portugol studio.

Estou utilizando macOS Mojave.

Alguma sugestão?

**Comment by JorgeNachtigall** [comment]
Bom, o instalador "visual" não funcionou, porém copiando os arquivos do plugin para o diretório citado na mensagem de errou possibilitou eu utilizar o meu plugin/bibliotecas.

`Caused by: java.io.FileNotFoundException: /Applications/Portugol Studio.app/Contents/Resources/IDE/plugins/Plugin-Exemplo./ExemploPlugin.jar (No such file or directory)`

Fiz manualmente e deu certo.

**Comment by AdsonEsteves** [comment]
@JorgeNachtigall Vou deixar aberto pois isso não deveria acontecer.
Vamos verificar.

**Comment by JorgeNachtigall** [comment]
> @JorgeNachtigall Vou deixar aberto pois isso não deveria acontecer.
> Vamos verificar.

No que eu puder ajudar estou a disposição.
