### ISSUE TITLE
Erro ArrayIndexOutOfBoundsException (24218c7a78f388e11a57e554d54c99c0922a2ea2) v2.7.4

### ISSUE THREAD

**Issue by kaduramos** [UNIVALI-LITE/Portugol-Studio#769]
br.univali.ps.nucleo.ExcecaoAplicacao: java.lang.ArrayIndexOutOfBoundsException: 101 >= 101
	at br.univali.ps.nucleo.TratadorExcecoes.uncaughtException(TratadorExcecoes.java:131)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.awt.EventDispatchThread.processException(EventDispatchThread.java:227)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:219)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 101 >= 101
	at java.util.Vector.elementAt(Vector.java:477)
	at javax.swing.undo.UndoManager.editToBeUndone(UndoManager.java:294)
	at javax.swing.undo.UndoManager.canUndo(UndoManager.java:431)
	at org.fife.ui.rtextarea.RUndoManager.updateActions(RUndoManager.java:194)
	at org.fife.ui.rtextarea.RTextArea$RTextAreaMutableCaretEvent.focusGained(RTextArea.java:1651)
	at java.awt.AWTEventMulticaster.focusGained(AWTEventMulticaster.java:220)
	at java.awt.AWTEventMulticaster.focusGained(AWTEventMulticaster.java:219)
	at java.awt.AWTEventMulticaster.focusGained(AWTEventMulticaster.java:219)
	at java.awt.AWTEventMulticaster.focusGained(AWTEventMulticaster.java:219)
	at java.awt.Component.processFocusEvent(Component.java:6428)
	at java.awt.Component.processEvent(Component.java:6295)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1015)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:639)
	at java.awt.Component.dispatchEventImpl(Component.java:4760)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	... 5 more

**Comment by AdsonEsteves** [comment]
@kaduramos 
O erro aconteceu com frequencia?
