### ISSUE TITLE
Erro NullPointerException ao salvar (fd5ee0927bf20c444baa33b2f4392d98f64d1eb4) v2.7.4

### ISSUE THREAD

**Issue by WesleySP** [UNIVALI-LITE/Portugol-Studio#773]
> Esta issue foi gerada automaticamente

[pressione o botao "copiar erro" no Portugol Studio e cole o erro aqui antes de enviar]

**Comment by WesleySP** [comment]
br.univali.ps.nucleo.ExcecaoAplicacao: java.lang.NullPointerException
	at br.univali.ps.nucleo.TratadorExcecoes.transformarExcecao(TratadorExcecoes.java:267)
	at br.univali.ps.nucleo.TratadorExcecoes.exibirExcecao(TratadorExcecoes.java:42)
	at br.univali.ps.ui.abas.AbaCodigoFonte.salvaArquivo(AbaCodigoFonte.java:932)
	at br.univali.ps.ui.abas.AbaCodigoFonte.access$1500(AbaCodigoFonte.java:105)
	at br.univali.ps.ui.abas.AbaCodigoFonte$21.actionPerformed(AbaCodigoFonte.java:995)
	at br.univali.ps.ui.abas.AbaCodigoFonte$20.actionPerformed(AbaCodigoFonte.java:893)
	at br.univali.ps.ui.abas.AbaCodigoFonte$21.actionPerformed(AbaCodigoFonte.java:997)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1668)
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2882)
	at javax.swing.KeyboardManager.fireBinding(KeyboardManager.java:307)
	at javax.swing.KeyboardManager.fireKeyboardAction(KeyboardManager.java:263)
	at javax.swing.JComponent.processKeyBindingsForAllComponents(JComponent.java:2974)
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2966)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2845)
	at java.awt.Component.processEvent(Component.java:6316)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:835)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1103)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:974)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:800)
	at java.awt.Component.dispatchEventImpl(Component.java:4760)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NullPointerException
	at br.univali.ps.ui.utils.FileHandle.save(FileHandle.java:19)
	at br.univali.ps.ui.utils.FileHandle.save(FileHandle.java:15)
	at br.univali.ps.ui.abas.AbaCodigoFonte.salvaArquivo(AbaCodigoFonte.java:926)
	... 43 more

**Comment by gustavorattmann** [comment]
Se estiver usando Linux, talvez esse comando resolva:
sudo chown -R $USER diretoriocompleto

Por exemplo, se for salvar dentro da pasta Documentos, faça esse comando
sudo chown -R $USER ~/Documents/nomedapasta
