### ISSUE TITLE
Erro "Não foi possível iniciar o Portugol" a59273cd202cf06c7533cc19cdff2e48e0668364 v2.7.4

### ISSUE THREAD

**Issue by LeoFernandes3** [UNIVALI-LITE/Portugol-Studio#774]
> Esta issue foi gerada automaticamente

[pressione o botao "copiar erro" no Portugol Studio e cole o erro aqui antes de enviar]
br.univali.ps.nucleo.ExcecaoAplicacao: N￣o foi poss￭vel iniciar o Portugol Studio
	at br.univali.ps.nucleo.PortugolStudio.exibirTelaPrincipal(PortugolStudio.java:798)
	at br.univali.ps.nucleo.PortugolStudio.iniciarNovaInstancia(PortugolStudio.java:259)
	at br.univali.ps.ui.Lancador.start(Lancador.java:278)
	at br.univali.ps.ui.Lancador.main(Lancador.java:73)
Caused by: java.lang.reflect.InvocationTargetException
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1349)
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1324)
	at javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1353)
	at br.univali.ps.nucleo.PortugolStudio.exibirTelaPrincipal(PortugolStudio.java:773)
	... 3 more
Caused by: java.lang.NoClassDefFoundError: org/apache/http/HttpEntity
	at br.univali.ps.ui.telas.TelaPrincipal.<init>(TelaPrincipal.java:49)
	at br.univali.ps.ui.window.OutsidePanel.initComponents(OutsidePanel.java:64)
	at br.univali.ps.ui.window.OutsidePanel.<init>(OutsidePanel.java:25)
	at br.univali.ps.nucleo.PortugolStudio$2.run(PortugolStudio.java:780)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: org.apache.http.HttpEntity
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more

**Comment by AdsonEsteves** [comment]
@LeoFernandes3 

Isso acontece ou aconteceu com frequencia?

**Comment by noschang** [comment]
@AdsonEsteves parece que o e erro é a falta da biblioteca Apache Http Components. Será que ele não está tentando rodar o Portugol direto pelo Java, sem passar pelos nossos launchers? Se for isso, pode ser que a biblioteca não esteja sendo referenciada no classpath
