### ISSUE TITLE
Erro numero 893c3d9397310a5c18e8e80ac17d5069558c9b36 v2.7.4

### ISSUE THREAD

**Issue by 11ange** [UNIVALI-LITE/Portugol-Studio#796]
> Esta issue foi gerada automaticamente

br.univali.ps.nucleo.ExcecaoAplicacao: java.io.IOException: O provedor do arquivo de nuvem n￣o est￡ em execu￧￣o
	at br.univali.ps.nucleo.TratadorExcecoes.transformarExcecao(TratadorExcecoes.java:267)
	at br.univali.ps.nucleo.TratadorExcecoes.exibirExcecao(TratadorExcecoes.java:42)
	at br.univali.ps.ui.paineis.PainelExemplos.atualizarRecentes(PainelExemplos.java:444)
	at br.univali.ps.ui.paineis.PainelExemplos.<init>(PainelExemplos.java:159)
	at br.univali.ps.ui.abas.AbaInicial.initComponents(AbaInicial.java:365)
	at br.univali.ps.ui.abas.AbaInicial.<init>(AbaInicial.java:44)
	at br.univali.ps.ui.telas.TelaPrincipal.criaAbas(TelaPrincipal.java:122)
	at br.univali.ps.ui.telas.TelaPrincipal.<init>(TelaPrincipal.java:65)
	at br.univali.ps.ui.window.OutsidePanel.initComponents(OutsidePanel.java:64)
	at br.univali.ps.ui.window.OutsidePanel.<init>(OutsidePanel.java:25)
	at br.univali.ps.nucleo.PortugolStudio$2.run(PortugolStudio.java:780)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.io.IOException: O provedor do arquivo de nuvem n￣o est￡ em execu￧￣o
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:233)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1792)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1769)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:1744)
	at org.apache.commons.io.IOUtils.toByteArray(IOUtils.java:462)
	at br.univali.ps.ui.utils.FileHandle.read(FileHandle.java:66)
	at br.univali.ps.ui.utils.FileHandle.read(FileHandle.java:61)
	at br.univali.ps.ui.utils.FileHandle.open(FileHandle.java:56)
	at br.univali.ps.ui.paineis.PainelExemplos.atualizarRecentes(PainelExemplos.java:405)
	... 22 more

**Comment by AdsonEsteves** [comment]
@11ange 
Obrigado pelo reporte.
Pelo erro deve ter dado algum problema com seu Onedrive imagino.
Se o erro ocorre com frequência sugiro tentar dar uma olhada nessas soluções:

https://answers.microsoft.com/pt-br/windows/forum/all/erro-0x8007016a-o-provedor-do-arquivo-de-nuvem/7dd9740f-e88c-47cd-ab64-e6a85a54c725
http://windowsbulletin.com/pt/how-to-repair-error-0x8007016a-cloud-file-provider-is-not-running/

**Comment by 11ange** [comment]
@AdsonEsteves , obrigado pelo retorno. Reiniciei o onedrive e sumiu o erro.
Obrigado e continuem com o ótimo trabalho no Portugol!
Abraço!
