### ISSUE TITLE
Bugs no inspetor de variáveis

### ISSUE THREAD

**Issue by rytix** [UNIVALI-LITE/Portugol-Studio#82]
O código utilizado é um código exemplo localizado em: exemplos -> jogos -> serpente

1) Quando se tenta arrastar uma matriz que possui uma coluna constante para o inspetor de variáveis o inspetor não deixa.
![image](https://cloud.githubusercontent.com/assets/7809511/13231936/76196e9c-d98b-11e5-8b0a-39429979d4f5.png)

2) Alterando o valor que era constante para um valor numérico volta a ser possível arrastar para o inspetor de variáveis.
Ou deveria ser possível, mas outro bug apareceu na frente atrapalhando o relato do bug encontrado.
![image](https://cloud.githubusercontent.com/assets/7809511/13232335/894dde24-d98d-11e5-9121-945bfc8e2fa4.png)
A tela fica preta assim para sempre, e após apertar no OK, se mover o mouse para dentro do inspetor de variáveis o erro volta.

Update:
Foi detectado que na classe RenderizadorDeMatriz no método getAlturaPreferida ele tenta pegar a altura da FONTE_CABECALHO que é nula, gerando o NullPointerException.
![image](https://cloud.githubusercontent.com/assets/7809511/13260694/68e1903c-da3b-11e5-88dc-52c14b563238.png)

3) A variável não é atualizada no inspetor de variáveis se for declarada no inicio e mudar rapidamente só uma vez.
![image](https://cloud.githubusercontent.com/assets/7809511/13232797/7202258e-d98f-11e5-9eb6-d87e6e7d374f.png)
Passando o mouse em cima do inspetor de variáveis atualiza elas.

4)Existe um bug aonde se você declarar uma matriz com um tamanho definido (inteiro mat[5][5]), arrastar para o inspetor de variáveis, e alterar o valor para uma constante já declarada (inteiro const NUM = 5; inteiro mat[NUM][5]) ao rodar o programa ele joga uma exceção).

Infelizmente não consegui reproduzir este bug por causa do item nº 2.

**Comment by elieserdejesus** [comment]
@rytix , duas coisas
1 - Qual o seu nome? Pelo apelido do github não consigo ter a menor idéia de quem é você :)
2 - Se o deadline não estiver muito apertado eu gostaria de trabalhar nessa issue. Mas não vou poder trabalhar nisso nesse semana, acho que poderei na próxima. Posso assumir a issue?

**Comment by AlissonSteffens** [comment]
@elieserdejesus o @rytix é o Paulo **tan tan tan!!!**

**Comment by noschang** [comment]
Oi @elieserdejesus!

Pode assumir a issue sim!
Eu passei outra tarefa para o @rytix.

Valeu!!

**Comment by elieserdejesus** [comment]
Ah, agora sei de quem se trata :)

**Comment by rytix** [comment]
Eu sou o paulo :3

**Comment by noschang** [comment]
Corrigido no Pull Request #88.

**Comment by AdsonEsteves** [comment]
Problema voltou a acontecer

![image](https://cloud.githubusercontent.com/assets/8836540/21274722/c116510c-c3b0-11e6-8e81-b0a815dd117c.png)


@elieserdejesus pode resolver novamente?

**Comment by elieserdejesus** [comment]
@AdsonEsteves , não consegui reproduzir o problema aqui. Testei os casos mencionados anteriormente e todos funcionaram. Consegues reproduzir o bug e dar mais detalhes?

**Comment by AdsonEsteves** [comment]
@elieserdejesus estou atualizado e continua com o bug, simplesmente ao colocar qualquer matiz ou vetor no inspetor

![image](https://cloud.githubusercontent.com/assets/8836540/22436764/956c7e62-e70c-11e6-8e49-80586e7cc354.png)


Segue exceção


GRAVE [16:52:55:831]: Exceção capturada [br.univali.ps.nucleo.TratadorExcecoes exibirExcecao] 
br.univali.ps.nucleo.ExcecaoAplicacao: java.lang.NullPointerException
	at br.univali.ps.nucleo.TratadorExcecoes.uncaughtException(TratadorExcecoes.java:199)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.awt.EventDispatchThread.processException(EventDispatchThread.java:223)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:215)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:281)
	at sun.swing.SwingUtilities2.getFontMetrics(SwingUtilities2.java:1113)
	at javax.swing.JComponent.getFontMetrics(JComponent.java:1626)
	at br.univali.ps.ui.inspetor.RenderizadorDeVetor.getAlturaPreferida(RenderizadorDeVetor.java:33)
	at br.univali.ps.ui.inspetor.RenderizadorBase.atualizaDimensoes(RenderizadorBase.java:63)
	at br.univali.ps.ui.inspetor.RenderizadorBase.setItemDaLista(RenderizadorBase.java:68)
	at br.univali.ps.ui.inspetor.RenderizadorDeVetor.setItemDaLista(RenderizadorDeVetor.java:26)
	at br.univali.ps.ui.inspetor.ItemDaListaParaVetor.getRendererComponent(ItemDaListaParaVetor.java:97)
	at br.univali.ps.ui.inspetor.InspetorDeSimbolos$RenderizadorDaLista.getListCellRendererComponent(InspetorDeSimbolos.java:231)
	at br.univali.ps.ui.inspetor.InspetorDeSimbolos$RenderizadorDaLista.getListCellRendererComponent(InspetorDeSimbolos.java:219)
	at javax.swing.plaf.basic.BasicListUI.updateLayoutState(BasicListUI.java:1361)
	at javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1311)
	at javax.swing.plaf.basic.BasicListUI.getCellBounds(BasicListUI.java:996)
	at javax.swing.plaf.basic.BasicListUI.access$1400(BasicListUI.java:57)
	at javax.swing.plaf.basic.BasicListUI$Handler.repaintDropLocation(BasicListUI.java:2559)
	at javax.swing.plaf.basic.BasicListUI$Handler.propertyChange(BasicListUI.java:2544)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at java.awt.Component.firePropertyChange(Component.java:8428)
	at javax.swing.JList.setDropLocation(JList.java:1420)
	at javax.swing.TransferHandler$DropHandler.setComponentDropLocation(TransferHandler.java:1452)
	at javax.swing.TransferHandler$DropHandler.cleanup(TransferHandler.java:1570)
	at javax.swing.TransferHandler$DropHandler.drop(TransferHandler.java:1550)
	at java.awt.dnd.DropTarget.drop(DropTarget.java:455)
	at javax.swing.TransferHandler$SwingDropTarget.drop(TransferHandler.java:1282)
	at sun.awt.dnd.SunDropTargetContextPeer.processDropMessage(SunDropTargetContextPeer.java:538)
	at sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchDropEvent(SunDropTargetContextPeer.java:852)
	at sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchEvent(SunDropTargetContextPeer.java:776)
	at sun.awt.dnd.SunDropTargetEvent.dispatch(SunDropTargetEvent.java:48)
	at java.awt.Component.dispatchEventImpl(Component.java:4744)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processDropTargetEvent(Container.java:4599)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4461)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	... 5 more
 
GRAVE [16:52:55:921]: Exceção capturada [br.univali.ps.nucleo.TratadorExcecoes exibirExcecao] 
br.univali.ps.nucleo.ExcecaoAplicacao: java.lang.NullPointerException
	at br.univali.ps.nucleo.TratadorExcecoes.uncaughtException(TratadorExcecoes.java:199)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.awt.EventDispatchThread.processException(EventDispatchThread.java:223)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:215)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:869)
	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:666)
	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:637)
	at br.univali.ps.nucleo.TratadorExcecoes.exibirExcecaoSimples(TratadorExcecoes.java:105)
	at br.univali.ps.nucleo.TratadorExcecoes.exibir(TratadorExcecoes.java:98)
	at br.univali.ps.nucleo.TratadorExcecoes.exibirExcecao(TratadorExcecoes.java:64)
	at br.univali.ps.nucleo.TratadorExcecoes.uncaughtException(TratadorExcecoes.java:199)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.awt.EventDispatchThread.processException(EventDispatchThread.java:223)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:215)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:281)
	at sun.swing.SwingUtilities2.getFontMetrics(SwingUtilities2.java:1113)
	at javax.swing.JComponent.getFontMetrics(JComponent.java:1626)
	at br.univali.ps.ui.inspetor.RenderizadorDeVetor.getAlturaPreferida(RenderizadorDeVetor.java:33)
	at br.univali.ps.ui.inspetor.RenderizadorBase.atualizaDimensoes(RenderizadorBase.java:63)
	at br.univali.ps.ui.inspetor.RenderizadorBase.setItemDaLista(RenderizadorBase.java:68)
	at br.univali.ps.ui.inspetor.RenderizadorDeVetor.setItemDaLista(RenderizadorDeVetor.java:26)
	at br.univali.ps.ui.inspetor.ItemDaListaParaVetor.getRendererComponent(ItemDaListaParaVetor.java:97)
	at br.univali.ps.ui.inspetor.InspetorDeSimbolos$RenderizadorDaLista.getListCellRendererComponent(InspetorDeSimbolos.java:231)
	at br.univali.ps.ui.inspetor.InspetorDeSimbolos$RenderizadorDaLista.getListCellRendererComponent(InspetorDeSimbolos.java:219)
	at javax.swing.plaf.basic.BasicListUI.updateLayoutState(BasicListUI.java:1361)
	at javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1311)
	at javax.swing.plaf.basic.BasicListUI.getPreferredSize(BasicListUI.java:578)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1662)
	at javax.swing.ScrollPaneLayout.layoutContainer(ScrollPaneLayout.java:791)
	at java.awt.Container.layout(Container.java:1510)
	at java.awt.Container.doLayout(Container.java:1499)
	at java.awt.Container.validateTree(Container.java:1695)
	at java.awt.Container.validate(Container.java:1630)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:711)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:708)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1731)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	... 24 more
 
GRAVE [16:52:55:973]: Exceção capturada [br.univali.ps.nucleo.TratadorExcecoes exibirExcecao] 
br.univali.ps.nucleo.ExcecaoAplicacao: java.lang.NullPointerException
	at br.univali.ps.nucleo.TratadorExcecoes.uncaughtException(TratadorExcecoes.java:199)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.awt.EventDispatchThread.processException(EventDispatchThread.java:223)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:215)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:869)
	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:666)
	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:637)
	at br.univali.ps.nucleo.TratadorExcecoes.exibirExcecaoSimples(TratadorExcecoes.java:105)
	at br.univali.ps.nucleo.TratadorExcecoes.exibir(TratadorExcecoes.java:98)
	at br.univali.ps.nucleo.TratadorExcecoes.exibirExcecao(TratadorExcecoes.java:64)
	at br.univali.ps.nucleo.TratadorExcecoes.uncaughtException(TratadorExcecoes.java:199)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.awt.EventDispatchThread.processException(EventDispatchThread.java:223)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:215)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:869)
	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:666)
	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:637)
	at br.univali.ps.nucleo.TratadorExcecoes.exibirExcecaoSimples(TratadorExcecoes.java:105)
	at br.univali.ps.nucleo.TratadorExcecoes.exibir(TratadorExcecoes.java:98)
	at br.univali.ps.nucleo.TratadorExcecoes.exibirExcecao(TratadorExcecoes.java:64)
	at br.univali.ps.nucleo.TratadorExcecoes.uncaughtException(TratadorExcecoes.java:199)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.awt.EventDispatchThread.processException(EventDispatchThread.java:223)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:215)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:281)
	at sun.swing.SwingUtilities2.getFontMetrics(SwingUtilities2.java:1113)
	at javax.swing.JComponent.getFontMetrics(JComponent.java:1626)
	at br.univali.ps.ui.inspetor.RenderizadorDeVetor.getAlturaPreferida(RenderizadorDeVetor.java:33)
	at br.univali.ps.ui.inspetor.RenderizadorBase.atualizaDimensoes(RenderizadorBase.java:63)
	at br.univali.ps.ui.inspetor.RenderizadorBase.setItemDaLista(RenderizadorBase.java:68)
	at br.univali.ps.ui.inspetor.RenderizadorDeVetor.setItemDaLista(RenderizadorDeVetor.java:26)
	at br.univali.ps.ui.inspetor.ItemDaListaParaVetor.getRendererComponent(ItemDaListaParaVetor.java:97)
	at br.univali.ps.ui.inspetor.InspetorDeSimbolos$4.run(InspetorDeSimbolos.java:297)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	... 43 more
 
GRAVE [16:52:56:063]: Exceção capturada [br.univali.ps.nucleo.TratadorExcecoes exibirExcecao] 
br.univali.ps.nucleo.ExcecaoAplicacao: java.lang.NullPointerException
	at br.univali.ps.nucleo.TratadorExcecoes.uncaughtException(TratadorExcecoes.java:199)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.awt.EventDispatchThread.processException(EventDispatchThread.java:223)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:215)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:869)
	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:666)
	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:637)
	at br.univali.ps.nucleo.TratadorExcecoes.exibirExcecaoSimples(TratadorExcecoes.java:105)
	at br.univali.ps.nucleo.TratadorExcecoes.exibir(TratadorExcecoes.java:98)
	at br.univali.ps.nucleo.TratadorExcecoes.exibirExcecao(TratadorExcecoes.java:64)
	at br.univali.ps.nucleo.TratadorExcecoes.uncaughtException(TratadorExcecoes.java:199)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.awt.EventDispatchThread.processException(EventDispatchThread.java:223)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:215)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:869)
	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:666)
	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:637)
	at br.univali.ps.nucleo.TratadorExcecoes.exibirExcecaoSimples(TratadorExcecoes.java:105)
	at br.univali.ps.nucleo.TratadorExcecoes.exibir(TratadorExcecoes.java:98)
	at br.univali.ps.nucleo.TratadorExcecoes.exibirExcecao(TratadorExcecoes.java:64)
	at br.univali.ps.nucleo.TratadorExcecoes.uncaughtException(TratadorExcecoes.java:199)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.awt.EventDispatchThread.processException(EventDispatchThread.java:223)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:215)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:869)
	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:666)
	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:637)
	at br.univali.ps.nucleo.TratadorExcecoes.exibirExcecaoSimples(TratadorExcecoes.java:105)
	at br.univali.ps.nucleo.TratadorExcecoes.exibir(TratadorExcecoes.java:98)
	at br.univali.ps.nucleo.TratadorExcecoes.exibirExcecao(TratadorExcecoes.java:64)
	at br.univali.ps.nucleo.TratadorExcecoes.uncaughtException(TratadorExcecoes.java:199)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.awt.EventDispatchThread.processException(EventDispatchThread.java:223)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:215)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NullPointerException
