### ISSUE TITLE
"No such line"  numero f243e20dd85df3610bfc8cd3c02b8542121d7c1f v2.7.4

### ISSUE THREAD

**Issue by FabiianoDev** [UNIVALI-LITE/Portugol-Studio#857]
br.univali.ps.nucleo.ExcecaoAplicacao: javax.swing.text.BadLocationException: No such line
	at br.univali.ps.nucleo.TratadorExcecoes.transformarExcecao(TratadorExcecoes.java:267)
	at br.univali.ps.nucleo.TratadorExcecoes.exibirExcecao(TratadorExcecoes.java:42)
	at br.univali.ps.ui.editor.Editor.posicionarCursor(Editor.java:1541)
	at br.univali.ps.ui.editor.Editor.exibirMensagemCompilador(Editor.java:1516)
	at br.univali.ps.ui.editor.Editor.mensagemCompiladorSelecionada(Editor.java:1497)
	at br.univali.ps.ui.abas.AbaMensagemCompilador.notificarMensagemSelecionada(AbaMensagemCompilador.java:115)
	at br.univali.ps.ui.abas.AbaMensagemCompilador.lambda$instalarObservadores$0(AbaMensagemCompilador.java:84)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:184)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:164)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:211)
	at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:405)
	at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:415)
	at javax.swing.DefaultListSelectionModel.setSelectionInterval(DefaultListSelectionModel.java:459)
	at javax.swing.JTable.changeSelectionModel(JTable.java:2392)
	at javax.swing.JTable.changeSelection(JTable.java:2461)
	at javax.swing.plaf.basic.BasicTableUI$Handler.adjustSelection(BasicTableUI.java:1115)
	at javax.swing.plaf.basic.BasicTableUI$Handler.mousePressed(BasicTableUI.java:1038)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.Component.processMouseEvent(Component.java:6536)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4532)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: javax.swing.text.BadLocationException: No such line
	at javax.swing.JTextArea.getLineStartOffset(JTextArea.java:409)
	at br.univali.ps.ui.editor.Editor.posicionarCursor(Editor.java:1528)
	... 47

**Comment by AdsonEsteves** [comment]
@FabiianoDev 
Como ocorreu esse erro? Acontece sempre?
