### ISSUE TITLE
Erro numero 4c478dd74e06f351e51fa391bdf39470df7779dd v2.7.5

### ISSUE THREAD

**Issue by Geissoncr** [UNIVALI-LITE/Portugol-Studio#898]
> Esta issue foi gerada automaticamente

br.univali.ps.nucleo.ExcecaoAplicacao: java.io.FileNotFoundException: /tmp/mozilla_geissoncarlos0/calculadora2.0.por (Permissￃﾣo negada)
	at br.univali.ps.nucleo.TratadorExcecoes.transformarExcecao(TratadorExcecoes.java:278)
	at br.univali.ps.nucleo.TratadorExcecoes.exibirExcecao(TratadorExcecoes.java:43)
	at br.univali.ps.ui.abas.AbaCodigoFonte.salvaArquivo(AbaCodigoFonte.java:928)
	at br.univali.ps.ui.abas.AbaCodigoFonte.access$1500(AbaCodigoFonte.java:102)
	at br.univali.ps.ui.abas.AbaCodigoFonte$21.actionPerformed(AbaCodigoFonte.java:989)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1668)
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2882)
	at javax.swing.KeyboardManager.fireBinding(KeyboardManager.java:307)
	at javax.swing.KeyboardManager.fireKeyboardAction(KeyboardManager.java:263)
	at javax.swing.JComponent.processKeyBindingsForAllComponents(JComponent.java:2974)
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2966)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2845)
	at java.awt.Component.processEvent(Component.java:6316)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:835)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1103)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:974)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:800)
	at java.awt.Component.dispatchEventImpl(Component.java:4760)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.io.FileNotFoundException: /tmp/mozilla_geissoncarlos0/calculadora2.0.por (Permissￃﾣo negada)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at br.univali.ps.ui.utils.FileHandle.save(FileHandle.java:21)
	at br.univali.ps.ui.utils.FileHandle.save(FileHandle.java:15)
	at br.univali.ps.ui.abas.AbaCodigoFonte.salvaArquivo(AbaCodigoFonte.java:922)
	... 41 more

Código do Erro:
programa
{

	//Prof. Geisson, tive dificuldade com a entrada de numero negativos 
	//e também tem um problema no programa; 
	//ele acaba de somar, mostra o resultado e 
	//pede o numero de novo e o zero não funciona. 
	//Preciso mudar a logica pra ficar 100%...
	
	funcao inicio()
	{
		inteiro numero1 
		inteiro numero2
		inteiro resultado
		inteiro operacao

		
			
			escreva("\n\nDigite\n1) somar\n2) subtrair\n3) dividir\n4) multiplicar\n0) zero para sair: ")
			leia(operacao)
			
			enquanto (operacao != 0){

			
			escreva("Digite o 1º número: ")
			leia(numero1)
			escreva("Digite o 2º número: ")
			leia(numero2)
	
			se (operacao == 1){
				resultado = numero1 + numero2
				escreva("Valor da soma: ", resultado)
				inicio()
				}
			senao se (operacao == 2){
				resultado = numero1 - numero2
				escreva("Valor da subtração: ", resultado)
				inicio()
				}
			senao se(operacao == 3){
				se(numero2 > numero1 ou numero2 == numero1){
					escreva("Numero 2 não pode ser maior ou igual que numero 1\n")
				}senao{
					resultado = numero1 / numero2
					escreva("Valor da divisão: ", resultado)
					inicio()
					}
					
				}
				senao se (operacao == 4){
					resultado = numero1 * numero2
					escreva("Valor da multiplicação: ", resultado)
					inicio()
				}
				
			

	}
				
}
}

**Comment by AdsonEsteves** [comment]
@Geissoncr
De acordo com #793 você pode não ter permissão como usuário para escrever arquivos
utilizando o comando dando permissão ao seu usuário à pasta
`$ sudo chown -R $USER nomedodiretorio`
pode resolver

**Comment by AdsonEsteves** [comment]
Duplicate of #793
