### ISSUE TITLE
Erro numero b074771bba0d997d9910ee3eaf2602a548f87b2d v2.7.5

### ISSUE THREAD

**Issue by musaranho007** [UNIVALI-LITE/Portugol-Studio#925]
> Esta issue foi gerada automaticamente

[pressione o botao "copiar erro" no Portugol Studio e cole o erro aqui antes de enviar]

**Comment by musaranho007** [comment]
br.univali.ps.nucleo.ExcecaoAplicacao: br.univali.ps.plugins.base.ErroInstalacaoPlugin: Erro ao instalar o plugin 'Python.por'
	at br.univali.ps.nucleo.TratadorExcecoes.transformarExcecao(TratadorExcecoes.java:278)
	at br.univali.ps.nucleo.TratadorExcecoes.exibirExcecao(TratadorExcecoes.java:43)
	at br.univali.ps.plugins.base.GerenciadorPlugins$1.run(GerenciadorPlugins.java:118)
	at java.lang.Thread.run(Thread.java:748)
Caused by: br.univali.ps.plugins.base.ErroInstalacaoPlugin: Erro ao instalar o plugin 'Python.por'
	... 2 more
Caused by: java.io.FileNotFoundException: C:\Users\Daniel\Python.por (O sistema n￣o pode encontrar o arquivo especificado)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at br.univali.ps.ui.utils.UnzipUtility.unzip(UnzipUtility.java:35)
	at br.univali.ps.plugins.base.GerenciadorPlugins$1.run(GerenciadorPlugins.java:116)
	... 1 more

**Comment by AdsonEsteves** [comment]
@musaranho007 
Como ocorreu?
Pelo erro parece que você tentou instalar um plugin com um ".por"

**Comment by Mateus-Hirt** [comment]
Tentando instalar um plugin por um arquivo que não existe. Qualquer tentativa disso gera o mesmo erro.
Tentei instalar um plugin por um arquivo inexistente (teste.psa), para testar:

> br.univali.ps.nucleo.ExcecaoAplicacao: br.univali.ps.plugins.base.ErroInstalacaoPlugin: Erro ao instalar o plugin 'teste.psa'
> 	at br.univali.ps.nucleo.TratadorExcecoes.transformarExcecao(TratadorExcecoes.java:278)
> 	at br.univali.ps.nucleo.TratadorExcecoes.exibirExcecao(TratadorExcecoes.java:43)
> 	at br.univali.ps.plugins.base.GerenciadorPlugins$1.run(GerenciadorPlugins.java:118)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: br.univali.ps.plugins.base.ErroInstalacaoPlugin: Erro ao instalar o plugin 'teste.psa'
> 	... 2 more
> Caused by: java.io.FileNotFoundException: C:\Users\Usuario\Desktop\teste.psa (O sistema n￣o pode encontrar o arquivo especificado)
> 	at java.io.FileInputStream.open0(Native Method)
> 	at java.io.FileInputStream.open(FileInputStream.java:195)
> 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
> 	at br.univali.ps.ui.utils.UnzipUtility.unzip(UnzipUtility.java:35)
> 	at br.univali.ps.plugins.base.GerenciadorPlugins$1.run(GerenciadorPlugins.java:116)
> 	... 1 more
