### ISSUE TITLE
Nova tela inicial está bugando no MAC

### ISSUE THREAD

**Issue by elieserdejesus** [UNIVALI-LITE/Portugol-Studio#93]
No Mac (Mavericks) a nova tela inicial está apresentando esse erro. Depois do erro a árvore dos exemplos no lado esquerdo não é construída.

![screen shot 2016-03-01 at 10 15 06 am](https://cloud.githubusercontent.com/assets/1012741/13428032/92d16100-df96-11e5-9d63-73af6fdacc04.png)

Segue o stack trace:
```
GRAVE: Exceção capturada [br.univali.ps.nucleo.TratadorExcecoes exibirExcecao] 
java.lang.ClassCastException: javax.swing.tree.DefaultMutableTreeNode cannot be cast to br.univali.ps.ui.swing.components.ExampleMutableTreeNode
	at br.univali.ps.ui.swing.components.painelExemplos.lambda$initTreeListner$2(painelExemplos.java:136)
	at javax.swing.JTree.fireValueChanged(JTree.java:2927)
	at javax.swing.JTree$TreeSelectionRedirector.valueChanged(JTree.java:3391)
	at javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(DefaultTreeSelectionModel.java:635)
	at javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(DefaultTreeSelectionModel.java:1093)
	at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(DefaultTreeSelectionModel.java:294)
	at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPath(DefaultTreeSelectionModel.java:188)
	at javax.swing.JTree.setSelectionPath(JTree.java:1634)
	at br.univali.ps.ui.swing.components.painelExemplos.lambda$jTreedoClick$1(painelExemplos.java:76)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by AlissonSteffens** [comment]
Esse é fácil... O erro ocorre quando o projeto **Portugol-Studio-Recursos** está desatualizado.. @elieserdejesus tenta atualizar e me diz se o erro persiste. A criação da árvore depende de alguns arquivos que foram criados neste projeto

**Comment by elieserdejesus** [comment]
Hum, faz sentido. Eu atualizei todos os projetos que estão na lista de dependências do Portugol-Studio, mas o Portugol-Studio-Recursos não faz parte dessa lista. Vou testar novamente e dou um feedback...

**Comment by elieserdejesus** [comment]
@AlissonSteffens , tinhas razão. Atualizei o Portugol-Studio-Recursos e está funcionando corretamente. Fechando a issue...

**Comment by AlissonSteffens** [comment]
Eu já tinha documentado isso no Readme do PortugolStudio
![image](https://cloud.githubusercontent.com/assets/6234230/13434415/899721b0-dfb4-11e5-8eb6-b023575a1762.png)
