### ISSUE TITLE
Erro numero 7ad59447c9f126f23542d2d2757befae9eef9019 v2.7.5

### ISSUE THREAD

**Issue by tavarinasp** [UNIVALI-LITE/Portugol-Studio#933]
> Esta issue foi gerada automaticamente

[pressione o botao "copiar erro" no Portugol Studio e cole o erro aqui antes de enviar]
br.univali.ps.nucleo.ExcecaoAplicacao: java.lang.OutOfMemoryError: Java heap space
	at br.univali.ps.nucleo.TratadorExcecoes.uncaughtException(TratadorExcecoes.java:145)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.awt.EventDispatchThread.processException(EventDispatchThread.java:227)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:219)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.OutOfMemoryError: Java heap space

Código do Erro:

**Comment by AdsonEsteves** [comment]
@tavarinasp 

Como ocorreu o erro?

**Comment by AlissonSteffens** [comment]
@AdsonEsteves lembra se nessa build nova o heap space está com algum limite fixo? Se não me engano em algum momento nós tinhamos permitido ele alocar isso dinamicamente

**Comment by AdsonEsteves** [comment]
@AlissonSteffens 
Se me lembro bem isso é definido pelo portugol-studio.bat que chama o portugol com os parâmetros certos.
