### ISSUE TITLE
Erro numero 56a1146a826291c39eb74228d386797fee4f79a3 v2.7.5

### ISSUE THREAD

**Issue by RafaellMoura** [UNIVALI-LITE/Portugol-Studio#934]
> Esta issue foi gerada automaticamente

[pressione o botao "copiar erro" no Portugol Studio e cole o erro aqui antes de enviar]br.univali.ps.nucleo.ExcecaoAplicacao: java.io.FileNotFoundException: /usr/local/portugol-studio/facaenquanto.por (Permissￃﾣo negada)
	at br.univali.ps.nucleo.TratadorExcecoes.transformarExcecao(TratadorExcecoes.java:278)
	at br.univali.ps.nucleo.TratadorExcecoes.exibirExcecao(TratadorExcecoes.java:43)
	at br.univali.ps.ui.abas.AbaCodigoFonte.salvaArquivo(AbaCodigoFonte.java:928)
	at br.univali.ps.ui.abas.AbaCodigoFonte.access$1500(AbaCodigoFonte.java:102)
	at br.univali.ps.ui.abas.AbaCodigoFonte$21.actionPerformed(AbaCodigoFonte.java:989)
	at br.univali.ps.ui.abas.AbaCodigoFonte$20.actionPerformed(AbaCodigoFonte.java:889)
	at br.univali.ps.ui.abas.AbaCodigoFonte$21.actionPerformed(AbaCodigoFonte.java:991)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.io.FileNotFoundException: /usr/local/portugol-studio/facaenquanto.por (Permissￃﾣo negada)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at br.univali.ps.ui.utils.FileHandle.save(FileHandle.java:21)
	at br.univali.ps.ui.utils.FileHandle.save(FileHandle.java:15)
	at br.univali.ps.ui.abas.AbaCodigoFonte.salvaArquivo(AbaCodigoFonte.java:922)
	... 44 more

Código do Erro:
programa
{
	
	funcao inicio()
	{
		real item, soma=0.0
		faca{
			escreva("item: ")
			leia(item)
			soma+=item
		}enquanto(item != 0)
		escreva("soma = "+soma)
	}
}

**Comment by RafaellMoura** [comment]
O programa não está permitindo salvar o arquivo e aparece essa mensagem de erro, porém ele executa normalmente.

**Comment by AdsonEsteves** [comment]
@RafaellMoura 
Tenta dar permissão ao seu usuário com

$ sudo chown -R $USER nomedodiretorio

**Comment by RafaellMoura** [comment]
> @RafaellMoura 
> Tenta dar permissão ao seu usuário com
> 
> $ sudo chown -R $USER nomedodiretorio

Obrigado Adson,
eu não sei o que ocorreu, mas já copiei e salvei o código do arquivo em um .doc pois o problema foi dentro do Portugol estúdio e apenas para esse arquivo; e essa mensagem de erro foi gerada automaticamente pelo próprio software. Eu só reportei. Como sugestão para os Devs da Univali.
