### ISSUE TITLE
Erro numero 980ab9dd7a6a3ccefb92df4bcbfc926645a21e17 v2.7.5

### ISSUE THREAD

**Issue by victor-san3** [UNIVALI-LITE/Portugol-Studio#972]
> Esta issue foi gerada automaticamente

br.univali.ps.nucleo.ExcecaoAplicacao: java.lang.ArrayIndexOutOfBoundsException: -2
	at br.univali.ps.nucleo.TratadorExcecoes.uncaughtException(TratadorExcecoes.java:145)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.awt.EventDispatchThread.processException(EventDispatchThread.java:227)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:219)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ArrayIndexOutOfBoundsException: -2
	at javax.swing.text.AbstractDocument$BranchElement.getElement(AbstractDocument.java:2350)
	at br.univali.ps.ui.rstautil.PortugolParser.adicionarErroAviso(PortugolParser.java:257)
	at br.univali.ps.ui.rstautil.PortugolParser.notificarErrosAvisos(PortugolParser.java:168)
	at br.univali.ps.ui.rstautil.PortugolParser.parse(PortugolParser.java:229)
	at org.fife.ui.rsyntaxtextarea.ParserManager.actionPerformed(ParserManager.java:157)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	... 5 more

Código do Erro:
programa
{
	inclua biblioteca Util
 --> U
	
	funcao inicio()
	{
		inteiro contador = 0, sorteio, maior = 0, menor = 0, soma = 0, cinco = 0
		caracter resposta
		
		escreva("{ EXERCÍCIO 044 - Números sorteados }\nVou sortear vários números.")
		escreva("\n---------------------------------------\n")

		faca {
			contador++
			sorteio = U.sorteia(1, 10)
			escreva("O ", contador, "º valor sorteado foi: ", sorteio)
			soma +=
			escreva("\nQuer sortear mais um número? [S/N] ")
			leia(resposta)
			
		} enquanto (resposta == 's' ou resposta == 'S')
		
	}
}

**Comment by AdsonEsteves** [comment]
@victor-san3 
Esse erro ocorre sempre? Com o mesmo código?
