### ISSUE TITLE
Erro numero 1a1019accaaf340a71d39872c163896d2fd55a59 v2.7.5

### ISSUE THREAD

**Issue by 1000Tsurus** [UNIVALI-LITE/Portugol-Studio#991]
> Esta issue foi gerada automaticamente

[pressione o botao "copiar erro" no Portugol Studio e cole o erro aqui antes de enviar]br.univali.ps.nucleo.ExcecaoAplicacao: java.lang.ArrayIndexOutOfBoundsException
	at br.univali.ps.nucleo.TratadorExcecoes.uncaughtException(TratadorExcecoes.java:145)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.awt.EventDispatchThread.processException(EventDispatchThread.java:227)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:219)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ArrayIndexOutOfBoundsException

Código do Erro:
programa
{
	
	funcao inicio()
	{
	    cadeia pessoas[] = {"Vinícius","Lucas","Guilherme","Cauli","Alexandre","Marcos","Matheus"}
	    inteiro num
	    caracter nome
	    logico registro = falso

	    escreva("Qual nome deseja buscar na lista? ")
	    leia(nome)

	    para(caracter i; i <= 7; i++){
	    	  se (pessoas[i] == nome){
	    	  	escreva("Esse nome está na lista de aprovados!")
	    	  	registro = verdadeiro
	    	  }
	    }
	    
	}
}

**Comment by AdsonEsteves** [comment]
@1000Tsurus 
Isso acontece sempre? Consegue repetir?
